#!/usr/bin/env python3
"""Source of truth for UI strings (en, ru). Generates App/SSMT/Resources/Localizable.xcstrings
and verifies that every key used in Swift sources exists.

Usage: scripts/strings.py generate | check
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "App/SSMT/Resources/Localizable.xcstrings")

STRINGS = {
    "action.stop": ("STOP", "STOP"),
    "action.stop.help": ("Mute the test signal immediately (Esc)", "Мгновенно заглушить тестовый сигнал (Esc)"),
    "noise.toggle": ("Noise on/off", "Шум вкл/выкл"),
    "noise.pink": ("Pink noise (random)", "Розовый шум (случайный)"),
    "noise.white": ("White noise", "Белый шум"),
    "noise.periodic": ("Periodic pink (fast)", "Периодический розовый (быстрый)"),
    "noise.periodic.hint": ("Fast mode: coherence is not meaningful with periodic noise.",
                            "Быстрый режим: с периодическим шумом когерентность не имеет смысла."),
    "engine.start": ("Start audio", "Запустить аудио"),
    "engine.stop": ("Stop audio", "Остановить аудио"),
    "delay.find": ("Find delay", "Найти задержку"),
    "delay.searching": ("Searching…", "Поиск…"),
    "delay.locked": ("DELAY LOCKED", "ЗАДЕРЖКА ЗАФИКСИРОВАНА"),
    "delay.unreliable": ("Delay not found reliably. Raise the level or check the microphone.",
                         "Задержка найдена ненадёжно. Поднимите уровень или проверьте микрофон."),
    "setup.source": ("Source", "Источник"),
    "setup.interface": ("Interface", "Интерфейс"),
    "setup.simulation": ("Simulation (virtual room)", "Симуляция (виртуальный зал)"),
    "setup.mic.channel": ("Microphone input", "Вход микрофона"),
    "setup.output.channel": ("Signal output", "Выход сигнала"),
    "setup.ref.channel": ("Reference input", "Вход референса"),
    "setup.no48k": ("Device does not support 48 kHz", "Устройство не поддерживает 48 кГц"),
    "setup.reference": ("Reference", "Референс"),
    "setup.temperature": ("Air temperature", "Температура воздуха"),
    "setup.refresh": ("Refresh device list", "Обновить список устройств"),
    "setup.generator": ("Generator", "Генератор"),
    "setup.noise": ("Signal", "Сигнал"),
    "setup.level": ("Level", "Уровень"),
    "setup.max.level": ("Maximum level", "Максимальный уровень"),
    "setup.output.level": ("Output now", "Выход сейчас"),
    "ref.internal": ("Internal (no cable)", "Внутренний (без кабеля)"),
    "ref.loopback": ("Loopback cable", "Кабель loopback"),
    "ref.internal.hint": ("The generated signal is the reference. Only the microphone and one output are needed.",
                          "Референс — сам генерируемый сигнал. Нужны только микрофон и один выход."),
    "ref.loopback.hint": ("Connect a cable from the signal output to the reference input.",
                          "Соедините кабелем выход сигнала со входом референса."),
    "safety.hf.warning": ("High noise levels can damage HF drivers. Raise the level gradually.",
                          "Высокий уровень шума может повредить ВЧ-драйверы. Поднимайте уровень постепенно."),
    "permission.denied": ("Microphone access denied. Allow SSMT in System Settings → Privacy & Security → Microphone.",
                          "Нет доступа к микрофону. Разрешите SSMT в Системных настройках → Конфиденциальность и безопасность → Микрофон."),
    "sim.title": ("Virtual system", "Виртуальная система"),
    "sim.hint": ("Simulates muting groups on the processor.", "Имитирует мьют групп на процессоре."),
    "sim.sub": ("Subwoofers on", "Сабвуферы включены"),
    "sim.main": ("Mains (satellites) on", "Сателлиты включены"),
    "display.title": ("Display", "Отображение"),
    "display.smoothing": ("Smoothing", "Сглаживание"),
    "display.smoothing.none": ("None", "Нет"),
    "display.coherence.threshold": ("Coherence threshold", "Порог когерентности"),
    "display.reset.avg": ("Reset averages", "Сбросить усреднение"),
    "display.reset.clip": ("Reset clip", "Сбросить клиппинг"),
    "settings.language": ("Language", "Язык"),
    "language.system": ("System", "Системный"),
    "meters.title": ("Inputs", "Входы"),
    "meters.mic": ("Microphone", "Микрофон"),
    "meters.ref": ("Reference", "Референс"),
    "meters.clip": ("CLIP", "КЛИП"),
    "meters.coherence": ("Coherence", "Когерентность"),
    "meters.averages": ("Averages", "Усреднений"),
    "meters.delay": ("Delay", "Задержка"),
    "quality.good": ("Good", "Хорошо"),
    "quality.weak": ("Weak", "Слабо"),
    "quality.repeat": ("Repeat", "Повторить"),
    "quality.none": ("No data", "Нет данных"),
    "graphs.title": ("Transfer function", "Передаточная функция"),
    "graphs.empty": ("Start the audio and the noise to see the measurement.",
                     "Запустите аудио и шум, чтобы увидеть измерение."),
    "graph.magnitude": ("Magnitude", "АЧХ"),
    "graph.phase": ("Phase", "Фаза"),
    "graph.coherence": ("Coherence", "Когерентность"),
    "action.cancel": ("Cancel", "Отмена"),
    "setup.split": ("Separate input and output devices", "Разные устройства для входа и выхода"),
    "setup.split.hint": ("SSMT creates a private aggregate device with drift correction so both run on one clock.",
                         "SSMT создаст частное агрегатное устройство с коррекцией дрейфа, чтобы вход и выход работали от одних часов."),
    "setup.input.device": ("Microphone device", "Устройство микрофона"),
    "setup.output.device": ("Output device", "Устройство выхода"),
    "autolevel.run": ("Auto level", "Автоуровень"),
    "autolevel.help": ("Measures room noise, then raises the level until SNR ≥ 20 dB or the maximum level.",
                       "Замеряет шум помещения, затем поднимает уровень до SNR ≥ 20 dB или до максимального уровня."),
    "autolevel.noise": ("Measuring room noise — keep quiet…", "Замер шума помещения — тишина…"),
    "autolevel.raising": ("Raising level…", "Поднимаю уровень…"),
    "autolevel.ok": ("Level %.0f dBFS · SNR %.0f dB", "Уровень %.0f dBFS · SNR %.0f dB"),
    "autolevel.max": ("Maximum reached · SNR only %.0f dB", "Достигнут максимум · SNR только %.0f dB"),
    "autolevel.clipped": ("Clipping — level reduced", "Клиппинг — уровень снижен"),
    "cal.title": ("Calibration", "Калибровка"),
    "cal.mic": ("Microphone", "Микрофон"),
    "cal.mic.none": ("No correction", "Без коррекции"),
    "cal.mic.uncalibrated": ("No microphone correction", "Без коррекции микрофона"),
    "cal.points": ("%ld points", "%ld точек"),
    "cal.remove": ("Remove from library", "Удалить из библиотеки"),
    "cal.import": ("Import calibration file…", "Импорт файла калибровки…"),
    "cal.spl": ("SPL calibration", "Калибровка SPL"),
    "cal.spl.none": ("SPL not calibrated", "SPL не откалиброван"),
    "cal.apply": ("Apply", "Применить"),
    "cal.calibrator": ("Read calibrator", "Считать калибратор"),
    "cal.calibrator.help": ("Put the calibrator on the microphone; the test signal is switched off.",
                            "Наденьте калибратор на микрофон; тестовый сигнал будет выключен."),
    "spl.reset": ("Reset SPL", "Сбросить SPL"),
    "mode.wizard": ("Wizard", "Мастер"),
    "mode.expert": ("Expert", "Эксперт"),
    "mode.stage": ("Stage", "Сцена"),
    "wizard.step.0": ("Prepare", "Подготовка"),
    "wizard.step.1": ("System", "Система"),
    "wizard.step.2": ("Subs", "Сабы"),
    "wizard.step.3": ("Mains", "Топы"),
    "wizard.step.4": ("Tune", "Тюнер"),
    "wizard.step.5": ("Verify", "Проверка"),
    "wizard.step.6": ("Zone", "Зона"),
    "wizard.step.7": ("EQ", "EQ"),
    "wizard.step.8": ("EQ check", "Проверка EQ"),
    "wizard.step.9": ("Done", "Готово"),
    "wizard.begin": ("Start setup", "Начать настройку"),
    "wizard.back": ("Back", "Назад"),
    "wizard.restart": ("New setup", "Новая настройка"),
    "wizard.next.eq": ("Next: EQ over the listening area", "Далее: EQ по зоне прослушивания"),
    "prep.title": ("Preparation", "Подготовка"),
    "prep.text": ("Place the measurement microphone at the main listening position, pointing at the system. Go through the checklist.",
                  "Поставьте измерительный микрофон в основную точку прослушивания, направив на систему. Пройдите список проверки."),
    "prep.checklist": ("Checklist", "Список проверки"),
    "prep.audio": ("Audio interface", "Звуковая карта"),
    "prep.audio.hint": ("Choose the interface on the left and start the audio.", "Выберите карту слева и запустите аудио."),
    "prep.mic": ("Microphone signal", "Сигнал микрофона"),
    "prep.mic.ok": ("Signal present, no clipping.", "Сигнал есть, клиппинга нет."),
    "prep.mic.clip": ("Clipping! Turn the microphone preamp down.", "Клиппинг! Уменьшите усиление микрофонного входа."),
    "prep.mic.hint": ("No signal from the microphone — check phantom power and the input.",
                      "Нет сигнала с микрофона — проверьте фантомное питание и вход."),
    "prep.level": ("Room noise and level", "Шум помещения и уровень"),
    "prep.level.hint": ("Keep quiet for 5 s, then the noise rises slowly to a safe working level.",
                        "5 с тишины, затем шум плавно поднимется до безопасного рабочего уровня."),
    "prep.delay": ("System delay", "Задержка системы"),
    "prep.delay.hint": ("All loudspeakers on. The delay is found once and locked for the whole setup.",
                        "Все громкоговорители включены. Задержка находится один раз и фиксируется на всю настройку."),
    "prep.system": ("Your system", "Ваша система"),
    "prep.hasSub": ("The system has subwoofers", "В системе есть сабвуферы"),
    "prep.knownCrossover": ("I know the crossover frequency", "Я знаю частоту раздела"),
    "prep.crossover.auto": ("Detected automatically", "Определится автоматически"),
    "prep.delayStep": ("Processor delay step", "Шаг задержки процессора"),
    "prep.levelStep": ("Processor level step", "Шаг уровня процессора"),
    "prep.fastMode.warning": ("Fast mode derives the mains from \"whole system − subs\". Less accurate near dips; nothing in the system may change between captures.",
                              "Быстрый режим вычисляет топы как «вся система − сабы». Менее точно около провалов; между замерами в системе ничего не должно меняться."),
    "capture.1.title": ("Whole system", "Вся система"),
    "capture.1.text": ("Turn ON all loudspeakers: subwoofers and mains. This is the \"before\" reference.",
                       "Включите ВСЕ громкоговорители: сабвуферы и топы. Это контрольный замер «до»."),
    "capture.2.title": ("Subwoofers only", "Только сабвуферы"),
    "capture.2.text": ("Mute the mains (satellites) on the processor. Leave only the subwoofers on.",
                       "Замьютьте сателлиты (топы) на процессоре. Оставьте включёнными только сабвуферы."),
    "capture.3.title": ("Mains only", "Только топы"),
    "capture.3.text": ("Unmute the mains and mute the subwoofers.", "Включите сателлиты и замьютьте сабвуферы."),
    "capture.5.title": ("Verification", "Проверка"),
    "capture.5.text": ("Enter the settings on the processor, turn ON all loudspeakers and capture again.",
                       "Введите настройки в процессор, включите ВСЕ громкоговорители и сделайте замер."),
    "capture.start": ("Capture", "Замер"),
    "capture.repeat": ("Repeat capture", "Повторить замер"),
    "capture.progress": ("Capture", "Замер"),
    "capture.accepted": ("Capture accepted", "Замер принят"),
    "capture.acceptedWeak": ("Accepted, but the signal was weak", "Принят, но сигнал был слабым"),
    "capture.rejected": ("Capture not accepted:", "Замер не принят:"),
    "capture.streamRestarted": ("The audio stream restarted — the delay must be found again and the captures repeated.",
                                "Аудиопоток перезапустился — нужно заново найти задержку и повторить замеры."),
    "reason.clipping": ("clipping at the microphone input.", "клиппинг на входе микрофона."),
    "reason.lowCoherence": ("the measurement is unstable (noise, wind, people talking, or the group is not on).",
                            "измерение нестабильно (шум, ветер, разговоры или нужная группа не включена)."),
    "reason.tooFewAverages": ("too short.", "слишком короткий."),
    "reason.streamDiscontinuity": ("audio dropout during the capture.", "пропуск аудио во время замера."),
    "group.subs": ("Subwoofers", "Сабвуферы"),
    "group.mains": ("Mains (satellites)", "Сателлиты (топы)"),
    "group.on": ("ON", "ВКЛ"),
    "group.muted": ("MUTED", "МЬЮТ"),
    "sim.doIt": ("Simulation: do it for me", "Симуляция: сделать за меня"),
    "sim.applySettings": ("Simulation: enter the settings on the virtual processor", "Симуляция: ввести настройки в виртуальный процессор"),
    "results.title": ("Tune by the needle", "Настройте по стрелке"),
    "results.text": ("The cards show the target. Turn the knobs on your processor while watching the needles — like a guitar tuner — until everything is green.",
                     "Карточки — это цель. Крутите ручки процессора, глядя на стрелки, как в гитарном тюнере, пока всё не станет зелёным."),
    "results.failed": ("Could not compute the alignment. Repeat the captures (louder, or another microphone position).",
                       "Не удалось рассчитать выравнивание. Повторите замеры (громче или с другой позиции микрофона)."),
    "results.ambiguous": ("The solution is ambiguous: another setting sums almost as well. Better: repeat the captures from another microphone position.",
                          "Решение неоднозначно: другая настройка складывается почти так же. Лучше повторить замеры с другой позиции микрофона."),
    "results.prediction": ("Expected result", "Ожидаемый результат"),
    "results.applied": ("I entered the settings → verify", "Я ввёл настройки → проверка"),
    "card.delay.sub": ("Subwoofer delay", "Задержка сабвуфера"),
    "card.delay.mains": ("Mains delay", "Задержка топов"),
    "card.polarity": ("Subwoofer polarity", "Полярность сабвуфера"),
    "polarity.normal": ("Normal", "Прямая"),
    "polarity.invert": ("Invert", "Инвертировать"),
    "card.level": ("Subwoofer level", "Уровень сабвуфера"),
    "curve.before": ("Before", "До"),
    "curve.prediction": ("Prediction", "Прогноз"),
    "curve.after": ("After", "После"),
    "verdict.excellent": ("Excellent", "Отлично"),
    "verdict.excellent.text": ("The subwoofers and mains now add up in the crossover region.", "Сабвуферы и топы теперь складываются в зоне раздела."),
    "verdict.goodBut": ("Good, but…", "Хорошо, но…"),
    "verdict.goodBut.text": ("Summation improved, but not as much as predicted.", "Сложение улучшилось, но меньше, чем ожидалось."),
    "verdict.checkSettings": ("Check polarity and delay", "Проверьте полярность и задержку"),
    "verdict.checkSettings.text": ("The result does not match the prediction.", "Результат не совпадает с прогнозом."),
    "verify.dip": ("Crossover dip", "Провал на кроссовере"),
    "verify.sum": ("Summation", "Сложение"),
    "verify.predictionError": ("Deviation from prediction", "Отклонение от прогноза"),
    "verify.curves": ("Before / prediction / after", "До / прогноз / после"),
    "verify.again": ("Repeat verification", "Повторить проверку"),
    "advice.polarityNotApplied": ("Looks like the polarity was not changed. Check the subwoofer polarity on the processor.",
                                  "Похоже, полярность не изменена. Проверьте полярность сабвуфера в процессоре."),
    "advice.delayNotApplied": ("Looks like the delay was not entered. Check the delay on the processor.",
                               "Похоже, задержка не введена. Проверьте задержку в процессоре."),
    "advice.delayWrongSign": ("The delay seems to be on the wrong group (subs vs mains).", "Похоже, задержка введена не той группе (сабы ↔ топы)."),
    "advice.levelMismatch": ("The level change seems not to be applied.", "Похоже, изменение уровня не применено."),
    "advice.conditionsChanged": ("Something changed since the captures (microphone position, processor settings, people in the room). Repeat the setup.",
                                 "С момента замеров что-то изменилось (позиция микрофона, настройки процессора, люди в зале). Повторите настройку."),
    "finished.title": ("Done", "Готово"),
    "tuner.waiting": ("Listening…", "Слушаю…"),
    "tuner.unreliable": ("Unstable signal", "Сигнал нестабилен"),
    "tuner.inTune": ("IN TUNE", "В СТРОЮ"),
    "tuner.sub.more": ("Add subwoofer delay", "Добавьте задержку сабвуферу"),
    "tuner.sub.less": ("Reduce subwoofer delay", "Уменьшите задержку сабвуфера"),
    "tuner.mains.more": ("Add mains delay", "Добавьте задержку топам"),
    "tuner.mains.less": ("Reduce mains delay", "Уменьшите задержку топов"),
    "tuner.level.up": ("Turn the subwoofer up", "Прибавьте уровень сабвуфера"),
    "tuner.level.down": ("Turn the subwoofer down", "Убавьте уровень сабвуфера"),
    "tuner.polarity.switch": ("Switch polarity", "Переключите полярность"),
    "tuner.polarity.ok": ("Correct", "Верно"),
    "tuner.next.mains": ("Subwoofer done → mains delay", "Сабвуфер готов → задержка топов"),
    "tuner.verify.ready": ("All in tune → verify", "Всё в строю → проверка"),
    "vproc.title": ("Virtual processor", "Виртуальный процессор"),
    "vproc.subDelay": ("Sub delay", "Задержка саба"),
    "vproc.mainsDelay": ("Mains delay", "Задержка топов"),
    "vproc.subLevel": ("Sub level", "Уровень саба"),
    "vproc.subPolarity": ("Sub polarity inverted", "Полярность саба инвертирована"),
    "unit.ms": ("ms", "мс"),
    "launch.loading": ("Loading…", "Загрузка…"),
    "about.title": ("About SSMT", "О программе"),
    "about.text": ("A toolkit for sound engineers. Function 1: automatic sound system setup.",
                   "Набор инструментов звукорежиссёра. Функция 1: автоматическая настройка акустической системы."),
    "about.splash": ("Show splash screen at launch", "Показывать заставку при запуске"),
    "mini.toggle": ("Mini window", "Мини-окно"),
    "mini.opacity": ("Opacity", "Прозрачность"),
    "mini.clickThrough": ("Click-through (turn off in the SSMT menu)", "Клики насквозь (выключить в меню SSMT)"),
    "mini.clickThroughOff": ("Mini window: clicks back on", "Мини-окно: вернуть клики"),
    "mini.expand": ("Expand", "Развернуть"),
    "mini.noDelay": ("delay not locked", "задержка не зафиксирована"),
    "report.title": ("System setup report", "Отчёт о настройке системы"),
    "report.alignment": ("Subwoofer alignment", "Выравнивание сабвуфера"),
    "report.verification": ("Verification", "Проверка"),
    "report.eq": ("EQ over the listening area", "EQ по зоне прослушивания"),
    "report.conditions": ("Conditions", "Условия"),
    "report.group": ("Group", "Группа"),
    "report.pdf": ("Export report (PDF)…", "Экспорт отчёта (PDF)…"),
    "report.png": ("Export report (PNG)…", "Экспорт отчёта (PNG)…"),
    "report.copy": ("Copy report as text", "Скопировать отчёт текстом"),
    "session.open": ("Open session…", "Открыть сессию…"),
    "session.save": ("Save session…", "Сохранить сессию…"),
    "gauge.quality": ("Signal quality", "Качество сигнала"),
    "gauge.quality.good": ("Good — ready", "Хорошо — можно мерить"),
    "gauge.quality.weak": ("Weak — quieter or louder", "Слабо — тише или громче"),
    "gauge.quality.bad": ("Bad — check group and silence", "Плохо — проверьте группу и тишину"),
    "gauge.quality.clip": ("Clipping — lower the mic gain", "Клиппинг — убавьте микрофон"),
    "gauge.snr": ("Signal / noise", "Сигнал / шум"),
    "gauge.snr.good": ("Enough", "Достаточно"),
    "gauge.snr.low": ("Too low — raise the level", "Мало — поднимите уровень"),
    "gauge.snr.needNoise": ("Run auto level", "Нужен автоуровень"),
    "gauge.deviation": ("Deviation from target", "Отклонение от цели"),
    "gauge.score": ("Quality score", "Оценка качества"),
    "gauge.score.note": ("The score is a guide, not a guarantee.", "Оценка — ориентир, а не гарантия."),
    "gauge.before": ("before: %.1f dB", "было: %.1f dB"),
    "gauge.beforeScore": ("before: %ld", "было: %ld"),
    "gauge.matches": ("Matches the prediction", "Совпадает с прогнозом"),
    "gauge.differs": ("Differs from the prediction", "Отличается от прогноза"),
    "capture.ready": ("Wait for the needle to turn green, then press Capture.", "Дождитесь зелёной стрелки и нажмите «Замер»."),
    "capture.running": ("Measuring — keep quiet, don't move the microphone.", "Идёт замер — тишина, микрофон не двигать."),
    "eq.point.rejected": ("Point not accepted:", "Точка не принята:"),
    "eq.capturePoint": ("Capture point %ld", "Замер точки %ld"),
    "eq.compute": ("Calculate EQ", "Рассчитать EQ"),
    "eq.iterate": ("One more correction round", "Ещё одна итерация коррекции"),
    "eq.finish": ("Finish", "Завершить"),
    "eq.target": ("Target curve", "Целевая кривая"),
    "eq.map": ("Measurement points", "Точки замера"),
    "eq.map.stage": ("STAGE", "СЦЕНА"),
    "target.flat": ("Flat", "Плоская"),
    "target.livePA": ("Live / PA", "Живой звук / PA"),
    "target.speech": ("Speech", "Речь"),
    "target.club": ("Club", "Клуб"),
    "target.custom": ("Custom", "Пользовательская"),
    "target.editor": ("Target curve editor", "Редактор целевой кривой"),
    "target.editor.hint": ("Points are joined in log frequency; the curve is flat beyond the first and last point. The level is aligned to the measurement automatically.",
                           "Точки соединяются в логарифмической шкале частот; за крайними точками кривая горизонтальна. Уровень подстраивается к замеру автоматически."),
    "target.addPoint": ("Add point", "Добавить точку"),
    "target.startFrom": ("Start from preset", "Взять за основу"),
    "eq.tune.title": ("Enter the EQ", "Введите EQ"),
    "eq.tune.text": ("Leave the microphone at point 1. Start the tuner, then enter the bands one by one on the processor: the needle shows how many dB are still missing.",
                     "Оставьте микрофон в точке 1. Запустите тюнер и вводите полосы по одной в процессор: стрелка показывает, сколько dB ещё не хватает."),
    "eq.tune.start": ("Start EQ tuner", "Запустить тюнер EQ"),
    "eq.tune.entered": ("Bands entered → check over the area", "Полосы введены → проверка по зоне"),
    "eq.tune.allSet": ("All in tune → check over the area", "Всё в строю → проверка по зоне"),
    "eq.nothingToDo": ("The response is already close to the target — no EQ needed.", "АЧХ уже близка к цели — EQ не нужен."),
    "eq.bands": ("EQ bands", "Полосы EQ"),
    "eq.band.title": ("Band %ld · %@", "Полоса %ld · %@"),
    "eq.band.cutMore": ("Cut %.1f dB more", "Убавьте ещё %.1f dB"),
    "eq.band.boostMore": ("Add %.1f dB", "Прибавьте %.1f dB"),
    "eq.band.shape": ("Gain is right — check frequency and Q", "Усиление верное — проверьте частоту и Q"),
    "eq.overall": ("EQ vs plan", "EQ против плана"),
    "eq.curves": ("EQ: plan and entered", "EQ: план и введено"),
    "curve.plan": ("Plan", "План"),
    "curve.entered": ("Entered", "Введено"),
    "sim.movePoint": ("Simulation: move the microphone to point %ld", "Симуляция: перенести микрофон в точку %ld"),
    "export.copy": ("Copy filters", "Скопировать фильтры"),
    "noise.short": ("Noise", "Шум"),
    "mode.title": ("Mode", "Режим"),
    "settings.open": ("Audio and calibration…", "Звук и калибровка…"),
    "settings.title": ("Audio and calibration", "Звук и калибровка"),
    "settings.done": ("Done", "Готово"),
    "prep.info": ("Put the measurement microphone at the main listening position, at ear height, pointing at the system. Start the audio, run auto level (5 s of silence, then a slow rise) and find the delay with all loudspeakers on.", "Поставьте измерительный микрофон в основную точку прослушивания на высоте ушей, направив на систему. Запустите аудио, затем автоуровень (5 с тишины, потом плавный подъём) и найдите задержку при включённых громкоговорителях."),
    "prep.change": ("Change", "Изменить"),
    "prep.level.noise": ("Silence…", "Тишина…"),
    "prep.level.raising": ("Rising…", "Подъём…"),
    "prep.delay.bad": ("Not reliable", "Ненадёжно"),
    "capture.1.short": ("All loudspeakers on", "Включите все громкоговорители"),
    "capture.2.short": ("Mains muted, subs on", "Топы — мьют, сабы — включены"),
    "capture.3.short": ("Subs muted, mains on", "Сабы — мьют, топы — включены"),
    "capture.5.short": ("Settings entered, everything on", "Настройки введены, всё включено"),
    "results.subtitle": ("Turn the knobs until everything is green", "Крутите ручки, пока всё не станет зелёным"),
    "results.ambiguous.short": ("Ambiguous solution — better repeat from another mic position", "Решение неоднозначно — лучше повторить с другой точки"),
    "finished.subtitle": ("Settings and result", "Настройки и результат"),
    "report.pdf.short": ("Report PDF", "Отчёт PDF"),
    "report.png.short": ("PNG", "PNG"),
    "export.text.short": ("Filters TXT", "Фильтры TXT"),
    "session.save.short": ("Session", "Сессия"),
    "eq.points.subtitle": ("Microphone at ear height", "Микрофон — на высоте ушей"),
    "eq.points.info": ("Measure the points shown on the map, spread over the listening area. A point with low quality or clipping is rejected — just repeat it.", "Обойдите точки по схеме, равномерно по зоне прослушивания. Точка с низким качеством или клиппингом не принимается — просто повторите её."),
    "eq.verify.done": ("EQ result", "Результат EQ"),
    "eq.points.done": ("All points measured", "Все точки измерены"),
    "eq.points.point": ("Point %ld of %ld", "Точка %ld из %ld"),
    "eq.verify.point": ("Check: point %ld of %ld", "Проверка: точка %ld из %ld"),
    "eq.pointCount.title": ("Points", "Точек"),
    "eq.tune.subtitle": ("Band by band, by the needle", "Полоса за полосой, по стрелке"),
    "eq.tune.reference.short": ("Listens 6 s first — enter nothing yet", "Сначала 6 с слушает — пока ничего не вводите"),
    "group.subs.tag": ("SUB", "САБ"),
    "group.mains.tag": ("TOP", "ТОП"),
    "stage.counter": ("Step %ld of %ld", "Шаг %ld из %ld"),
    "stage.0.title": ("Preparation", "Подготовка"),
    "stage.0.subtitle": ("System check", "Проверка системы"),
    "stage.1.title": ("Measurements", "Замеры"),
    "stage.1.subtitle": ("System, subs, mains", "Система, сабы, топы"),
    "stage.2.title": ("Alignment", "Выравнивание"),
    "stage.2.subtitle": ("Delay, polarity, level", "Задержка, полярность, уровень"),
    "stage.3.title": ("EQ", "EQ"),
    "stage.3.subtitle": ("Frequency correction", "Частотная коррекция"),
    "stage.4.title": ("Done", "Готово"),
    "stage.4.subtitle": ("Report and export", "Отчёт и экспорт"),
    "status.off": ("Audio off", "Аудио выключено"),
    "status.running": ("Audio running", "Аудио работает"),
    "status.ready": ("System ready", "Система готова"),
    "prep.fastMode.short": ("Fast mode", "Быстрый режим"),
    "cal.section.files": ("Your calibration files", "Ваши файлы калибровки"),
    "cal.section.measurement": ("Measurement microphones", "Измерительные микрофоны"),
    "cal.section.smallDiaphragm": ("Small-diaphragm condensers", "Конденсаторные, малая мембрана"),
    "cal.section.largeDiaphragm": ("Large-diaphragm condensers", "Конденсаторные, большая мембрана"),
    "cal.section.dynamic": ("Dynamic", "Динамические"),
    "cal.individual": ("Individual calibration", "Индивидуальная калибровка"),
    "cal.typical": ("Typical curve ±2–3 dB", "Типовая кривая ±2–3 дБ"),
    "cal.typical.note": ("Model response from published charts, not your sample. Load the individual file if you have one.", "АЧХ модели по графикам производителя, а не вашего экземпляра. Есть индивидуальный файл — загрузите его."),
    "cal.typical.flat": ("Nominally flat", "Номинально ровный"),
    "cal.typical.flat.note": ("Almost no correction. Use the individual calibration file supplied with the microphone.", "Коррекция почти нулевая. Используйте индивидуальный файл калибровки из комплекта микрофона."),
    "cal.cardioid.note": ("Cardioid: in a room the top end reads lower than on axis. Point it at the system; for EQ an omni measurement mic is more honest.", "Кардиоида: в зале верх читается ниже, чем на оси. Направьте на систему; для EQ честнее всенаправленный измерительный микрофон."),
    "prep.mic.profile": ("Microphone profile", "Профиль микрофона"),
    "prep.mic.noProfile": ("Choose your microphone.", "Выберите свой микрофон."),
    "prep.mic.typical": ("Typical profile.", "Типовой профиль."),
    "graphics.reduced": ("Reduced graphics (older Macs)", "Облегчённая графика (старые Mac)"),
    "eq.grid.title": ("Band frequencies", "Частоты полос"),
    "eq.grid.thirdOctave": ("Standard 1/3 octave (ISO)", "Стандартные 1/3 октавы (ISO)"),
    "eq.grid.sixthOctave": ("Fine 1/6 octave (ISO)", "Точные 1/6 октавы (ISO)"),
    "eq.grid.free": ("Any frequency", "Любые частоты"),
    "error.audioLost": ("Audio stopped arriving from the interface (unplugged, driver stopped or the device was taken by another app). The measurement was stopped — check the connection and start the audio again; the delay will be found anew.", "Звук перестал поступать от звуковой карты (отключена, драйвер остановился или устройство занято другой программой). Замер остановлен — проверьте подключение и снова запустите аудио; задержку нужно будет найти заново."),
    "action.close": ("Close", "Закрыть"),
    "processor.title": ("Console / processor", "Пульт / процессор"),
    "processor.generic": ("Generic", "Общий"),
    "processor.custom": ("My console…", "Свой пульт…"),
    "processor.edit": ("Parameters", "Параметры"),
    "processor.verified": ("Confirmed:", "Подтверждено:"),
    "processor.rest": ("Everything else uses generic values.", "Остальное — общие значения."),
    "processor.source.behringer-x32": ("6-band PEQ on buses, matrices and main.", "6-полосный PEQ на шинах, матрицах и мастере."),
    "processor.source.ah-sq": ("output delay up to 682 ms, 4-band PEQ, width 1/9–1.5 octave.", "задержка выходов до 682 мс, 4-полосный PEQ, ширина 1/9–1.5 октавы."),
    "processor.source.yamaha-cl": ("output channels: 4-band PEQ, delay 0–1000 ms (an 8-band PEQ can also be mounted in the effect rack).", "выходные каналы: 4-полосный PEQ, задержка 0–1000 мс (8-полосный PEQ можно поставить и в рэк эффектов)."),
    "processor.maxDelay": ("Maximum output delay, ms (0 = unknown)", "Максимальная задержка выхода, мс (0 — неизвестно)"),
    "processor.bandsSub": ("PEQ bands on the sub output: %ld", "Полос PEQ на выходе сабов: %ld"),
    "processor.bandsMains": ("PEQ bands on the satellite output: %ld", "Полос PEQ на выходе сателлитов: %ld"),
    "processor.gainStep": ("PEQ gain step", "Шаг усиления PEQ"),
    "processor.octaves": ("Band width in octaves (not Q)", "Ширина полосы в октавах (а не Q)"),
    "processor.delayTooLong": ("%.2f ms is more than this console's maximum delay (%.0f ms). Delay the other group instead or use an external processor.", "%.2f мс — больше максимальной задержки этого пульта (%.0f мс). Задержите другую группу или используйте внешний процессор."),
    "processor.source.ah-dlive": ("mix output delay up to 682 ms (firmware 1.80+), 4-band PEQ; with NEQ12 instead of the GEQ, set 12 bands in “My console”.", "задержка выходов до 682 мс (прошивка 1.80+), 4-полосный PEQ; если на выходе стоит NEQ12 вместо GEQ — задайте 12 полос в «Своём пульте»."),
    "processor.source.midas-hd96": ("flexi aux / matrix outputs: 4-band PEQ, delay up to 500 ms.", "выходы flexi aux / матрицы: 4-полосный PEQ, задержка до 500 мс."),
    "processor.source.yamaha-tf": ("AUX and STEREO: 4-band PEQ. Output delay is not confirmed — check on your console; if there is none, delay the subs or satellites in an external processor.", "AUX и STEREO: 4-полосный PEQ. Задержка на выходах не подтверждена — проверьте на пульте; если её нет, задержку вводите во внешнем процессоре."),
    "processor.source.yamaha-rivage": ("output channels: 8-band PEQ, delay 0–1000 ms.", "выходные каналы: 8-полосный PEQ, задержка 0–1000 мс."),
}

DYNAMIC_PREFIXES = {
    "processor.source.": ["processor.source.behringer-x32", "processor.source.ah-sq", "processor.source.ah-dlive", "processor.source.midas-hd96", "processor.source.yamaha-cl", "processor.source.yamaha-tf", "processor.source.yamaha-rivage"],
    "error.": ["error.audioLost"],
    "eq.grid.": ["eq.grid.thirdOctave", "eq.grid.sixthOctave", "eq.grid.free"],
    "cal.section.": [f"cal.section.{k}" for k in ("measurement", "smallDiaphragm", "largeDiaphragm", "dynamic")],
    "stage.": [f"stage.{i}.{k}" for i in range(5) for k in ("title", "subtitle")],
    "graph.": ["graph.magnitude", "graph.phase", "graph.coherence"],
    "wizard.step.": [f"wizard.step.{i}" for i in range(10)],
    "target.": [f"target.{p}" for p in ("flat", "livePA", "speech", "club", "custom")],
    "capture.": [f"capture.{i}.{k}" for i in (1, 2, 3, 5) for k in ("title", "text", "short")],
    "reason.": ["reason.clipping", "reason.lowCoherence", "reason.tooFewAverages", "reason.streamDiscontinuity"],
    "verdict.": [f"verdict.{v}{t}" for v in ("excellent", "goodBut", "checkSettings") for t in ("", ".text")],
    "advice.": [f"advice.{a}" for a in ("polarityNotApplied", "delayNotApplied", "delayWrongSign", "levelMismatch", "conditionsChanged")],
}


def generate():
    catalog = {"sourceLanguage": "en", "version": "1.0", "strings": {}}
    for key in sorted(STRINGS):
        en, ru = STRINGS[key]
        catalog["strings"][key] = {
            "extractionState": "manual",
            "localizations": {
                "en": {"stringUnit": {"state": "translated", "value": en}},
                "ru": {"stringUnit": {"state": "translated", "value": ru}},
            },
        }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(catalog, f, ensure_ascii=False, indent=2)
        f.write("\n")


def check():
    used = set()
    for dirpath, _, files in os.walk(os.path.join(ROOT, "App")):
        for name in files:
            if name.endswith(".swift"):
                text = open(os.path.join(dirpath, name), encoding="utf-8").read()
                used |= set(re.findall(r'\.t\("([a-z0-9.]+)"', text))
                used |= set(re.findall(r'"((?:noise|ref|graph)\.[a-z.]+)"', text))
    missing = sorted(k for k in used if k not in STRINGS and not k.endswith("."))
    for keys in DYNAMIC_PREFIXES.values():
        missing += [k for k in keys if k not in STRINGS]
    generated = json.load(open(OUT, encoding="utf-8"))
    stale = sorted(set(STRINGS) ^ set(generated["strings"]))
    if missing or stale:
        print("Missing keys:", missing)
        print("Catalog out of date:", stale)
        sys.exit(1)
    print(f"OK: {len(used)} keys used, {len(STRINGS)} defined")


if __name__ == "__main__":
    {"generate": generate, "check": check}[sys.argv[1] if len(sys.argv) > 1 else "check"]()
