#!/usr/bin/env python3
"""Source of truth for UI strings (en, ru). Generates App/SSMT/Resources/Localizable.xcstrings
and verifies that every key used in Swift sources exists.

Usage: scripts/strings.py generate | check
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "App/SSMT/Resources/Localizable.xcstrings")

STRINGS = {
    "action.stop": ("STOP", "STOP"),
    "action.stop.help": ("Mute the test signal immediately (Esc)", "Мгновенно заглушить тестовый сигнал (Esc)"),
    "noise.toggle": ("Noise on/off", "Шум вкл/выкл"),
    "noise.pink": ("Pink noise (random)", "Розовый шум (случайный)"),
    "noise.white": ("White noise", "Белый шум"),
    "noise.periodic": ("Periodic pink (fast)", "Периодический розовый (быстрый)"),
    "noise.periodic.hint": ("Fast mode: coherence is not meaningful with periodic noise.",
                            "Быстрый режим: с периодическим шумом когерентность не имеет смысла."),
    "engine.start": ("Start audio", "Запустить аудио"),
    "engine.stop": ("Stop audio", "Остановить аудио"),
    "delay.find": ("Find delay", "Найти задержку"),
    "delay.searching": ("Searching…", "Поиск…"),
    "delay.locked": ("DELAY LOCKED", "ЗАДЕРЖКА ЗАФИКСИРОВАНА"),
    "delay.unreliable": ("Delay not found reliably. Raise the level or check the microphone.",
                         "Задержка найдена ненадёжно. Поднимите уровень или проверьте микрофон."),
    "setup.source": ("Source", "Источник"),
    "setup.interface": ("Interface", "Интерфейс"),
    "setup.simulation": ("Simulation (virtual room)", "Симуляция (виртуальный зал)"),
    "setup.mic.channel": ("Microphone input", "Вход микрофона"),
    "setup.output.channel": ("Signal output", "Выход сигнала"),
    "setup.ref.channel": ("Reference input", "Вход референса"),
    "setup.no48k": ("Device does not support 48 kHz", "Устройство не поддерживает 48 кГц"),
    "setup.reference": ("Reference", "Референс"),
    "setup.temperature": ("Air temperature", "Температура воздуха"),
    "setup.refresh": ("Refresh device list", "Обновить список устройств"),
    "setup.generator": ("Generator", "Генератор"),
    "setup.noise": ("Signal", "Сигнал"),
    "setup.level": ("Level", "Уровень"),
    "setup.max.level": ("Maximum level", "Максимальный уровень"),
    "setup.output.level": ("Output now", "Выход сейчас"),
    "ref.internal": ("Internal (no cable)", "Внутренний (без кабеля)"),
    "ref.loopback": ("Loopback cable", "Кабель loopback"),
    "ref.internal.hint": ("The generated signal is the reference. Only the microphone and one output are needed.",
                          "Референс — сам генерируемый сигнал. Нужны только микрофон и один выход."),
    "ref.loopback.hint": ("Connect a cable from the signal output to the reference input.",
                          "Соедините кабелем выход сигнала со входом референса."),
    "safety.hf.warning": ("High noise levels can damage HF drivers. Raise the level gradually.",
                          "Высокий уровень шума может повредить ВЧ-драйверы. Поднимайте уровень постепенно."),
    "permission.denied": ("Microphone access denied. Allow SSMT in System Settings → Privacy & Security → Microphone.",
                          "Нет доступа к микрофону. Разрешите SSMT в Системных настройках → Конфиденциальность и безопасность → Микрофон."),
    "sim.title": ("Virtual system", "Виртуальная система"),
    "sim.hint": ("Simulates muting groups on the processor.", "Имитирует мьют групп на процессоре."),
    "sim.sub": ("Subwoofers on", "Сабвуферы включены"),
    "sim.main": ("Mains (satellites) on", "Сателлиты включены"),
    "display.title": ("Display", "Отображение"),
    "display.smoothing": ("Smoothing", "Сглаживание"),
    "display.smoothing.none": ("None", "Нет"),
    "display.coherence.threshold": ("Coherence threshold", "Порог когерентности"),
    "display.reset.avg": ("Reset averages", "Сбросить усреднение"),
    "display.reset.clip": ("Reset clip", "Сбросить клиппинг"),
    "settings.language": ("Language", "Язык"),
    "language.system": ("System", "Системный"),
    "meters.title": ("Inputs", "Входы"),
    "meters.mic": ("Microphone", "Микрофон"),
    "meters.ref": ("Reference", "Референс"),
    "meters.clip": ("CLIP", "КЛИП"),
    "meters.coherence": ("Coherence", "Когерентность"),
    "meters.averages": ("Averages", "Усреднений"),
    "meters.delay": ("Delay", "Задержка"),
    "quality.good": ("Good", "Хорошо"),
    "quality.weak": ("Weak", "Слабо"),
    "quality.repeat": ("Repeat", "Повторить"),
    "quality.none": ("No data", "Нет данных"),
    "graphs.title": ("Transfer function", "Передаточная функция"),
    "graphs.empty": ("Start the audio and the noise to see the measurement.",
                     "Запустите аудио и шум, чтобы увидеть измерение."),
    "graph.magnitude": ("Magnitude", "АЧХ"),
    "graph.phase": ("Phase", "Фаза"),
    "graph.coherence": ("Coherence", "Когерентность"),
    "action.cancel": ("Cancel", "Отмена"),
    "setup.split": ("Separate input and output devices", "Разные устройства для входа и выхода"),
    "setup.split.hint": ("SSMT creates a private aggregate device with drift correction so both run on one clock.",
                         "SSMT создаст частное агрегатное устройство с коррекцией дрейфа, чтобы вход и выход работали от одних часов."),
    "setup.input.device": ("Microphone device", "Устройство микрофона"),
    "setup.output.device": ("Output device", "Устройство выхода"),
    "autolevel.run": ("Auto level", "Автоуровень"),
    "autolevel.help": ("Measures room noise, then raises the level until SNR ≥ 20 dB or the maximum level.",
                       "Замеряет шум помещения, затем поднимает уровень до SNR ≥ 20 dB или до максимального уровня."),
    "autolevel.noise": ("Measuring room noise — keep quiet…", "Замер шума помещения — тишина…"),
    "autolevel.raising": ("Raising level…", "Поднимаю уровень…"),
    "autolevel.ok": ("Level %.0f dBFS · SNR %.0f dB", "Уровень %.0f dBFS · SNR %.0f dB"),
    "autolevel.max": ("Maximum reached · SNR only %.0f dB", "Достигнут максимум · SNR только %.0f dB"),
    "autolevel.clipped": ("Clipping — level reduced", "Клиппинг — уровень снижен"),
    "cal.title": ("Calibration", "Калибровка"),
    "cal.mic": ("Microphone", "Микрофон"),
    "cal.mic.none": ("No correction", "Без коррекции"),
    "cal.mic.uncalibrated": ("No microphone correction", "Без коррекции микрофона"),
    "cal.points": ("%ld points", "%ld точек"),
    "cal.remove": ("Remove from library", "Удалить из библиотеки"),
    "cal.import": ("Import calibration file…", "Импорт файла калибровки…"),
    "cal.spl": ("SPL calibration", "Калибровка SPL"),
    "cal.spl.none": ("SPL not calibrated", "SPL не откалиброван"),
    "cal.apply": ("Apply", "Применить"),
    "cal.calibrator": ("Read calibrator", "Считать калибратор"),
    "cal.calibrator.help": ("Put the calibrator on the microphone; the test signal is switched off.",
                            "Наденьте калибратор на микрофон; тестовый сигнал будет выключен."),
    "spl.reset": ("Reset SPL", "Сбросить SPL"),
    "mode.wizard": ("Wizard", "Мастер"),
    "mode.expert": ("Expert", "Эксперт"),
    "mode.stage": ("Stage", "Сцена"),
    "wizard.step.0": ("Prepare", "Подготовка"),
    "wizard.step.1": ("System", "Система"),
    "wizard.step.2": ("Subs", "Сабы"),
    "wizard.step.3": ("Mains", "Топы"),
    "wizard.step.4": ("Tune", "Тюнер"),
    "wizard.step.5": ("Verify", "Проверка"),
    "wizard.step.6": ("Zone", "Зона"),
    "wizard.step.7": ("EQ", "EQ"),
    "wizard.step.8": ("EQ check", "Проверка EQ"),
    "wizard.step.9": ("Done", "Готово"),
    "wizard.begin": ("Start setup", "Начать настройку"),
    "wizard.back": ("Back", "Назад"),
    "wizard.restart": ("New setup", "Новая настройка"),
    "wizard.next.eq": ("Next: EQ over the listening area", "Далее: EQ по зоне прослушивания"),
    "prep.title": ("Preparation", "Подготовка"),
    "prep.text": ("Place the measurement microphone at the main listening position, pointing at the system. Go through the checklist.",
                  "Поставьте измерительный микрофон в основную точку прослушивания, направив на систему. Пройдите список проверки."),
    "prep.checklist": ("Checklist", "Список проверки"),
    "prep.audio": ("Audio interface", "Звуковая карта"),
    "prep.audio.hint": ("Choose the interface on the left and start the audio.", "Выберите карту слева и запустите аудио."),
    "prep.mic": ("Microphone signal", "Сигнал микрофона"),
    "prep.mic.ok": ("Signal present, no clipping.", "Сигнал есть, клиппинга нет."),
    "prep.mic.clip": ("Clipping! Turn the microphone preamp down.", "Клиппинг! Уменьшите усиление микрофонного входа."),
    "prep.mic.hint": ("No signal from the microphone — check phantom power and the input.",
                      "Нет сигнала с микрофона — проверьте фантомное питание и вход."),
    "prep.level": ("Room noise and level", "Шум помещения и уровень"),
    "prep.level.hint": ("Keep quiet for 5 s, then the noise rises slowly to a safe working level.",
                        "5 с тишины, затем шум плавно поднимется до безопасного рабочего уровня."),
    "prep.delay": ("System delay", "Задержка системы"),
    "prep.delay.hint": ("All loudspeakers on. The delay is found once and locked for the whole setup.",
                        "Все громкоговорители включены. Задержка находится один раз и фиксируется на всю настройку."),
    "prep.system": ("Your system", "Ваша система"),
    "prep.hasSub": ("The system has subwoofers", "В системе есть сабвуферы"),
    "prep.knownCrossover": ("I know the crossover frequency", "Я знаю частоту раздела"),
    "prep.crossover.auto": ("Detected automatically", "Определится автоматически"),
    "prep.delayStep": ("Processor delay step", "Шаг задержки процессора"),
    "prep.levelStep": ("Processor level step", "Шаг уровня процессора"),
    "prep.fastMode.warning": ("Fast mode derives the mains from \"whole system − subs\". Less accurate near dips; nothing in the system may change between captures.",
                              "Быстрый режим вычисляет топы как «вся система − сабы». Менее точно около провалов; между замерами в системе ничего не должно меняться."),
    "capture.1.title": ("Whole system", "Вся система"),
    "capture.1.text": ("Turn ON all loudspeakers: subwoofers and mains. This is the \"before\" reference.",
                       "Включите ВСЕ громкоговорители: сабвуферы и топы. Это контрольный замер «до»."),
    "capture.2.title": ("Subwoofers only", "Только сабвуферы"),
    "capture.2.text": ("Mute the mains (satellites) on the processor. Leave only the subwoofers on.",
                       "Замьютьте сателлиты (топы) на процессоре. Оставьте включёнными только сабвуферы."),
    "capture.3.title": ("Mains only", "Только топы"),
    "capture.3.text": ("Unmute the mains and mute the subwoofers.", "Включите сателлиты и замьютьте сабвуферы."),
    "capture.5.title": ("Verification", "Проверка"),
    "capture.5.text": ("Enter the settings on the processor, turn ON all loudspeakers and capture again.",
                       "Введите настройки в процессор, включите ВСЕ громкоговорители и сделайте замер."),
    "capture.start": ("Capture", "Замер"),
    "capture.repeat": ("Repeat capture", "Повторить замер"),
    "capture.progress": ("Capture", "Замер"),
    "capture.accepted": ("Capture accepted", "Замер принят"),
    "capture.acceptedWeak": ("Accepted, but the signal was weak", "Принят, но сигнал был слабым"),
    "capture.rejected": ("Capture not accepted:", "Замер не принят:"),
    "capture.streamRestarted": ("The audio stream restarted — the delay must be found again and the captures repeated.",
                                "Аудиопоток перезапустился — нужно заново найти задержку и повторить замеры."),
    "reason.clipping": ("clipping at the microphone input.", "клиппинг на входе микрофона."),
    "reason.lowCoherence": ("the measurement is unstable (noise, wind, people talking, or the group is not on).",
                            "измерение нестабильно (шум, ветер, разговоры или нужная группа не включена)."),
    "reason.tooFewAverages": ("too short.", "слишком короткий."),
    "reason.streamDiscontinuity": ("audio dropout during the capture.", "пропуск аудио во время замера."),
    "group.subs": ("Subwoofers", "Сабвуферы"),
    "group.mains": ("Mains (satellites)", "Сателлиты (топы)"),
    "group.on": ("ON", "ВКЛ"),
    "group.muted": ("MUTED", "МЬЮТ"),
    "sim.doIt": ("Simulation: do it for me", "Симуляция: сделать за меня"),
    "sim.applySettings": ("Simulation: enter the settings on the virtual processor", "Симуляция: ввести настройки в виртуальный процессор"),
    "results.title": ("Tune by the needle", "Настройте по стрелке"),
    "results.text": ("The cards show the target. Turn the knobs on your processor while watching the needles — like a guitar tuner — until everything is green.",
                     "Карточки — это цель. Крутите ручки процессора, глядя на стрелки, как в гитарном тюнере, пока всё не станет зелёным."),
    "results.failed": ("Could not compute the alignment. Repeat the captures (louder, or another microphone position).",
                       "Не удалось рассчитать выравнивание. Повторите замеры (громче или с другой позиции микрофона)."),
    "results.ambiguous": ("The solution is ambiguous: another setting sums almost as well. Better: repeat the captures from another microphone position.",
                          "Решение неоднозначно: другая настройка складывается почти так же. Лучше повторить замеры с другой позиции микрофона."),
    "results.prediction": ("Expected result", "Ожидаемый результат"),
    "results.applied": ("I entered the settings → verify", "Я ввёл настройки → проверка"),
    "card.delay.sub": ("Subwoofer delay", "Задержка сабвуфера"),
    "card.delay.mains": ("Mains delay", "Задержка топов"),
    "card.polarity": ("Subwoofer polarity", "Полярность сабвуфера"),
    "polarity.normal": ("Normal", "Прямая"),
    "polarity.invert": ("Invert", "Инвертировать"),
    "card.level": ("Subwoofer level", "Уровень сабвуфера"),
    "curve.before": ("Before", "До"),
    "curve.prediction": ("Prediction", "Прогноз"),
    "curve.after": ("After", "После"),
    "verdict.excellent": ("Excellent", "Отлично"),
    "verdict.excellent.text": ("The subwoofers and mains now add up in the crossover region.", "Сабвуферы и топы теперь складываются в зоне раздела."),
    "verdict.goodBut": ("Good, but…", "Хорошо, но…"),
    "verdict.goodBut.text": ("Summation improved, but not as much as predicted.", "Сложение улучшилось, но меньше, чем ожидалось."),
    "verdict.checkSettings": ("Check polarity and delay", "Проверьте полярность и задержку"),
    "verdict.checkSettings.text": ("The result does not match the prediction.", "Результат не совпадает с прогнозом."),
    "verify.dip": ("Crossover dip", "Провал на кроссовере"),
    "verify.sum": ("Summation", "Сложение"),
    "verify.predictionError": ("Deviation from prediction", "Отклонение от прогноза"),
    "verify.curves": ("Before / prediction / after", "До / прогноз / после"),
    "verify.again": ("Repeat verification", "Повторить проверку"),
    "advice.polarityNotApplied": ("Looks like the polarity was not changed. Check the subwoofer polarity on the processor.",
                                  "Похоже, полярность не изменена. Проверьте полярность сабвуфера в процессоре."),
    "advice.delayNotApplied": ("Looks like the delay was not entered. Check the delay on the processor.",
                               "Похоже, задержка не введена. Проверьте задержку в процессоре."),
    "advice.delayWrongSign": ("The delay seems to be on the wrong group (subs vs mains).", "Похоже, задержка введена не той группе (сабы ↔ топы)."),
    "advice.levelMismatch": ("The level change seems not to be applied.", "Похоже, изменение уровня не применено."),
    "advice.conditionsChanged": ("Something changed since the captures (microphone position, processor settings, people in the room). Repeat the setup.",
                                 "С момента замеров что-то изменилось (позиция микрофона, настройки процессора, люди в зале). Повторите настройку."),
    "finished.title": ("Done", "Готово"),
    "tuner.waiting": ("Listening…", "Слушаю…"),
    "tuner.unreliable": ("Unstable signal", "Сигнал нестабилен"),
    "tuner.inTune": ("IN TUNE", "В СТРОЮ"),
    "tuner.sub.more": ("Add subwoofer delay", "Добавьте задержку сабвуферу"),
    "tuner.sub.less": ("Reduce subwoofer delay", "Уменьшите задержку сабвуфера"),
    "tuner.mains.more": ("Add mains delay", "Добавьте задержку топам"),
    "tuner.mains.less": ("Reduce mains delay", "Уменьшите задержку топов"),
    "tuner.level.up": ("Turn the subwoofer up", "Прибавьте уровень сабвуфера"),
    "tuner.level.down": ("Turn the subwoofer down", "Убавьте уровень сабвуфера"),
    "tuner.polarity.switch": ("Switch polarity", "Переключите полярность"),
    "tuner.polarity.ok": ("Correct", "Верно"),
    "tuner.next.mains": ("Subwoofer done → mains delay", "Сабвуфер готов → задержка топов"),
    "tuner.verify.ready": ("All in tune → verify", "Всё в строю → проверка"),
    "vproc.title": ("Virtual processor", "Виртуальный процессор"),
    "vproc.subDelay": ("Sub delay", "Задержка саба"),
    "vproc.mainsDelay": ("Mains delay", "Задержка топов"),
    "vproc.subLevel": ("Sub level", "Уровень саба"),
    "vproc.subPolarity": ("Sub polarity inverted", "Полярность саба инвертирована"),
    "unit.ms": ("ms", "мс"),
    "launch.loading": ("Loading…", "Загрузка…"),
    "about.title": ("About SSMT", "О программе"),
    "about.text": ("A toolkit for sound engineers. Function 1: automatic sound system setup.",
                   "Набор инструментов звукорежиссёра. Функция 1: автоматическая настройка акустической системы."),
    "about.splash": ("Show splash screen at launch", "Показывать заставку при запуске"),
    "mini.toggle": ("Mini window", "Мини-окно"),
    "mini.opacity": ("Opacity", "Прозрачность"),
    "mini.clickThrough": ("Click-through (turn off in the SSMT menu)", "Клики насквозь (выключить в меню SSMT)"),
    "mini.clickThroughOff": ("Mini window: clicks back on", "Мини-окно: вернуть клики"),
    "mini.expand": ("Expand", "Развернуть"),
    "mini.noDelay": ("delay not locked", "задержка не зафиксирована"),
    "report.title": ("System setup report", "Отчёт о настройке системы"),
    "report.alignment": ("Subwoofer alignment", "Выравнивание сабвуфера"),
    "report.verification": ("Verification", "Проверка"),
    "report.eq": ("EQ over the listening area", "EQ по зоне прослушивания"),
    "report.conditions": ("Conditions", "Условия"),
    "report.group": ("Group", "Группа"),
    "report.pdf": ("Export report (PDF)…", "Экспорт отчёта (PDF)…"),
    "report.png": ("Export report (PNG)…", "Экспорт отчёта (PNG)…"),
    "report.copy": ("Copy report as text", "Скопировать отчёт текстом"),
    "session.open": ("Open session…", "Открыть сессию…"),
    "session.save": ("Save session…", "Сохранить сессию…"),
    "gauge.quality": ("Signal quality", "Качество сигнала"),
    "gauge.quality.good": ("Good — ready", "Хорошо — можно мерить"),
    "gauge.quality.weak": ("Weak — quieter or louder", "Слабо — тише или громче"),
    "gauge.quality.bad": ("Bad — check group and silence", "Плохо — проверьте группу и тишину"),
    "gauge.quality.clip": ("Clipping — lower the mic gain", "Клиппинг — убавьте микрофон"),
    "gauge.snr": ("Signal / noise", "Сигнал / шум"),
    "gauge.snr.good": ("Enough", "Достаточно"),
    "gauge.snr.low": ("Too low — raise the level", "Мало — поднимите уровень"),
    "gauge.snr.needNoise": ("Run auto level", "Нужен автоуровень"),
    "gauge.deviation": ("Deviation from target", "Отклонение от цели"),
    "gauge.score": ("Quality score", "Оценка качества"),
    "gauge.score.note": ("The score is a guide, not a guarantee.", "Оценка — ориентир, а не гарантия."),
    "gauge.before": ("before: %.1f dB", "было: %.1f dB"),
    "gauge.beforeScore": ("before: %ld", "было: %ld"),
    "gauge.matches": ("Matches the prediction", "Совпадает с прогнозом"),
    "gauge.differs": ("Differs from the prediction", "Отличается от прогноза"),
    "capture.ready": ("Wait for the needle to turn green, then press Capture.", "Дождитесь зелёной стрелки и нажмите «Замер»."),
    "capture.running": ("Measuring — keep quiet, don't move the microphone.", "Идёт замер — тишина, микрофон не двигать."),
    "eq.point.rejected": ("Point not accepted:", "Точка не принята:"),
    "eq.capturePoint": ("Capture point %ld", "Замер точки %ld"),
    "eq.compute": ("Calculate EQ", "Рассчитать EQ"),
    "eq.iterate": ("One more correction round", "Ещё одна итерация коррекции"),
    "eq.finish": ("Finish", "Завершить"),
    "eq.target": ("Target curve", "Целевая кривая"),
    "eq.map": ("Measurement points", "Точки замера"),
    "eq.map.stage": ("STAGE", "СЦЕНА"),
    "target.flat": ("Flat", "Плоская"),
    "target.livePA": ("Live / PA", "Живой звук / PA"),
    "target.speech": ("Speech", "Речь"),
    "target.club": ("Club", "Клуб"),
    "target.custom": ("Custom", "Пользовательская"),
    "target.editor": ("Target curve editor", "Редактор целевой кривой"),
    "target.editor.hint": ("Points are joined in log frequency; the curve is flat beyond the first and last point. The level is aligned to the measurement automatically.",
                           "Точки соединяются в логарифмической шкале частот; за крайними точками кривая горизонтальна. Уровень подстраивается к замеру автоматически."),
    "target.addPoint": ("Add point", "Добавить точку"),
    "target.startFrom": ("Start from preset", "Взять за основу"),
    "eq.tune.title": ("Enter the EQ", "Введите EQ"),
    "eq.tune.text": ("Leave the microphone at point 1. Start the tuner, then enter the bands one by one on the processor: the needle shows how many dB are still missing.",
                     "Оставьте микрофон в точке 1. Запустите тюнер и вводите полосы по одной в процессор: стрелка показывает, сколько dB ещё не хватает."),
    "eq.tune.start": ("Start EQ tuner", "Запустить тюнер EQ"),
    "eq.tune.entered": ("Bands entered → check over the area", "Полосы введены → проверка по зоне"),
    "eq.tune.allSet": ("All in tune → check over the area", "Всё в строю → проверка по зоне"),
    "eq.nothingToDo": ("The response is already close to the target — no EQ needed.", "АЧХ уже близка к цели — EQ не нужен."),
    "eq.bands": ("EQ bands", "Полосы EQ"),
    "eq.band.title": ("Band %ld · %@", "Полоса %ld · %@"),
    "eq.band.cutMore": ("Cut %.1f dB more", "Убавьте ещё %.1f dB"),
    "eq.band.boostMore": ("Add %.1f dB", "Прибавьте %.1f dB"),
    "eq.band.shape": ("Gain is right — check frequency and Q", "Усиление верное — проверьте частоту и Q"),
    "eq.overall": ("EQ vs plan", "EQ против плана"),
    "eq.curves": ("EQ: plan and entered", "EQ: план и введено"),
    "curve.plan": ("Plan", "План"),
    "curve.entered": ("Entered", "Введено"),
    "sim.movePoint": ("Simulation: move the microphone to point %ld", "Симуляция: перенести микрофон в точку %ld"),
    "export.copy": ("Copy filters", "Скопировать фильтры"),
    "noise.short": ("Noise", "Шум"),
    "mode.title": ("Mode", "Режим"),
    "settings.open": ("Audio and calibration…", "Звук и калибровка…"),
    "settings.title": ("Audio and calibration", "Звук и калибровка"),
    "settings.done": ("Done", "Готово"),
    "prep.info": ("Put the measurement microphone at the main listening position, at ear height, pointing at the system. Start the audio, run auto level (5 s of silence, then a slow rise) and find the delay with all loudspeakers on.", "Поставьте измерительный микрофон в основную точку прослушивания на высоте ушей, направив на систему. Запустите аудио, затем автоуровень (5 с тишины, потом плавный подъём) и найдите задержку при включённых громкоговорителях."),
    "prep.change": ("Change", "Изменить"),
    "prep.level.noise": ("Silence…", "Тишина…"),
    "prep.level.raising": ("Rising…", "Подъём…"),
    "prep.delay.bad": ("Not reliable", "Ненадёжно"),
    "capture.1.short": ("All loudspeakers on", "Включите все громкоговорители"),
    "capture.2.short": ("Mains muted, subs on", "Топы — мьют, сабы — включены"),
    "capture.3.short": ("Subs muted, mains on", "Сабы — мьют, топы — включены"),
    "capture.5.short": ("Settings entered, everything on", "Настройки введены, всё включено"),
    "results.subtitle": ("Turn the knobs until everything is green", "Крутите ручки, пока всё не станет зелёным"),
    "results.ambiguous.short": ("Ambiguous solution — better repeat from another mic position", "Решение неоднозначно — лучше повторить с другой точки"),
    "finished.subtitle": ("Settings and result", "Настройки и результат"),
    "report.pdf.short": ("Report PDF", "Отчёт PDF"),
    "report.png.short": ("PNG", "PNG"),
    "export.text.short": ("Filters TXT", "Фильтры TXT"),
    "session.save.short": ("Session", "Сессия"),
    "eq.points.subtitle": ("Microphone at ear height", "Микрофон — на высоте ушей"),
    "eq.points.info": ("Measure the points shown on the map, spread over the listening area. A point with low quality or clipping is rejected — just repeat it.", "Обойдите точки по схеме, равномерно по зоне прослушивания. Точка с низким качеством или клиппингом не принимается — просто повторите её."),
    "eq.verify.done": ("EQ result", "Результат EQ"),
    "eq.points.done": ("All points measured", "Все точки измерены"),
    "eq.points.point": ("Point %ld of %ld", "Точка %ld из %ld"),
    "eq.verify.point": ("Check: point %ld of %ld", "Проверка: точка %ld из %ld"),
    "eq.pointCount.title": ("Points", "Точек"),
    "eq.tune.subtitle": ("Band by band, by the needle", "Полоса за полосой, по стрелке"),
    "eq.tune.reference.short": ("Listens 6 s first — enter nothing yet", "Сначала 6 с слушает — пока ничего не вводите"),
    "group.subs.tag": ("SUB", "САБ"),
    "group.mains.tag": ("TOP", "ТОП"),
    "stage.counter": ("Step %ld of %ld", "Шаг %ld из %ld"),
    "stage.0.title": ("Preparation", "Подготовка"),
    "stage.0.subtitle": ("System check", "Проверка системы"),
    "stage.1.title": ("Measurements", "Замеры"),
    "stage.1.subtitle": ("System, subs, mains", "Система, сабы, топы"),
    "stage.2.title": ("Alignment", "Выравнивание"),
    "stage.2.subtitle": ("Delay, polarity, level", "Задержка, полярность, уровень"),
    "stage.3.title": ("EQ", "EQ"),
    "stage.3.subtitle": ("Frequency correction", "Частотная коррекция"),
    "stage.4.title": ("Done", "Готово"),
    "stage.4.subtitle": ("Report and export", "Отчёт и экспорт"),
    "status.off": ("Audio off", "Аудио выключено"),
    "status.running": ("Audio running", "Аудио работает"),
    "status.ready": ("System ready", "Система готова"),
    "prep.fastMode.short": ("Fast mode", "Быстрый режим"),
    "cal.section.files": ("Your calibration files", "Ваши файлы калибровки"),
    "cal.section.measurement": ("Measurement microphones", "Измерительные микрофоны"),
    "cal.section.smallDiaphragm": ("Small-diaphragm condensers", "Конденсаторные, малая мембрана"),
    "cal.section.largeDiaphragm": ("Large-diaphragm condensers", "Конденсаторные, большая мембрана"),
    "cal.section.dynamic": ("Dynamic", "Динамические"),
    "cal.individual": ("Individual calibration", "Индивидуальная калибровка"),
    "cal.typical": ("Typical curve ±2–3 dB", "Типовая кривая ±2–3 дБ"),
    "cal.typical.note": ("Model response from published charts, not your sample. Load the individual file if you have one.", "АЧХ модели по графикам производителя, а не вашего экземпляра. Есть индивидуальный файл — загрузите его."),
    "cal.typical.flat": ("Nominally flat", "Номинально ровный"),
    "cal.typical.flat.note": ("Almost no correction. Use the individual calibration file supplied with the microphone.", "Коррекция почти нулевая. Используйте индивидуальный файл калибровки из комплекта микрофона."),
    "cal.cardioid.note": ("Cardioid: in a room the top end reads lower than on axis. Point it at the system; for EQ an omni measurement mic is more honest.", "Кардиоида: в зале верх читается ниже, чем на оси. Направьте на систему; для EQ честнее всенаправленный измерительный микрофон."),
    "prep.mic.profile": ("Microphone profile", "Профиль микрофона"),
    "prep.mic.noProfile": ("Choose your microphone.", "Выберите свой микрофон."),
    "prep.mic.typical": ("Typical profile.", "Типовой профиль."),
    "graphics.reduced": ("Reduced graphics (older Macs)", "Облегчённая графика (старые Mac)"),
    "eq.grid.title": ("Band frequencies", "Частоты полос"),
    "eq.grid.thirdOctave": ("Standard 1/3 octave (ISO)", "Стандартные 1/3 октавы (ISO)"),
    "eq.grid.sixthOctave": ("Fine 1/6 octave (ISO)", "Точные 1/6 октавы (ISO)"),
    "eq.grid.free": ("Any frequency", "Любые частоты"),
    "error.audioLost": ("Audio stopped arriving from the interface (unplugged, driver stopped or the device was taken by another app). The measurement was stopped — check the connection and start the audio again; the delay will be found anew.", "Звук перестал поступать от звуковой карты (отключена, драйвер остановился или устройство занято другой программой). Замер остановлен — проверьте подключение и снова запустите аудио; задержку нужно будет найти заново."),
    "action.close": ("Close", "Закрыть"),
    "processor.title": ("Console / processor", "Пульт / процессор"),
    "processor.generic": ("Generic", "Общий"),
    "processor.custom": ("My console…", "Свой пульт…"),
    "processor.edit": ("Parameters", "Параметры"),
    "processor.verified": ("Confirmed:", "Подтверждено:"),
    "processor.rest": ("Everything else uses generic values.", "Остальное — общие значения."),
    "processor.source.behringer-x32": ("6-band PEQ on buses, matrices and main.", "6-полосный PEQ на шинах, матрицах и мастере."),
    "processor.source.ah-sq": ("output delay up to 682 ms, 4-band PEQ, width 1/9–1.5 octave.", "задержка выходов до 682 мс, 4-полосный PEQ, ширина 1/9–1.5 октавы."),
    "processor.source.yamaha-cl": ("output channels: 4-band PEQ, delay 0–1000 ms (an 8-band PEQ can also be mounted in the effect rack).", "выходные каналы: 4-полосный PEQ, задержка 0–1000 мс (8-полосный PEQ можно поставить и в рэк эффектов)."),
    "processor.maxDelay": ("Maximum output delay, ms (0 = unknown)", "Максимальная задержка выхода, мс (0 — неизвестно)"),
    "processor.bandsSub": ("PEQ bands on the sub output: %ld", "Полос PEQ на выходе сабов: %ld"),
    "processor.bandsMains": ("PEQ bands on the satellite output: %ld", "Полос PEQ на выходе сателлитов: %ld"),
    "processor.gainStep": ("PEQ gain step", "Шаг усиления PEQ"),
    "processor.octaves": ("Band width in octaves (not Q)", "Ширина полосы в октавах (а не Q)"),
    "processor.delayTooLong": ("%.2f ms is more than this console's maximum delay (%.0f ms). Delay the other group instead or use an external processor.", "%.2f мс — больше максимальной задержки этого пульта (%.0f мс). Задержите другую группу или используйте внешний процессор."),
    "processor.source.ah-dlive": ("mix output delay up to 682 ms (firmware 1.80+), 4-band PEQ; with NEQ12 instead of the GEQ, set 12 bands in “My console”.", "задержка выходов до 682 мс (прошивка 1.80+), 4-полосный PEQ; если на выходе стоит NEQ12 вместо GEQ — задайте 12 полос в «Своём пульте»."),
    "processor.source.midas-hd96": ("flexi aux / matrix outputs: 4-band PEQ, delay up to 500 ms.", "выходы flexi aux / матрицы: 4-полосный PEQ, задержка до 500 мс."),
    "processor.source.yamaha-tf": ("AUX and STEREO: 4-band PEQ. Output delay is not confirmed — check on your console; if there is none, delay the subs or satellites in an external processor.", "AUX и STEREO: 4-полосный PEQ. Задержка на выходах не подтверждена — проверьте на пульте; если её нет, задержку вводите во внешнем процессоре."),
    "processor.source.yamaha-rivage": ("output channels: 8-band PEQ, delay 0–1000 ms.", "выходные каналы: 8-полосный PEQ, задержка 0–1000 мс."),
    "section.setup": ("System setup", "Настройка системы"),
    "section.inputList": ("Input list & stage plan", "Input list и сцена"),
    "action.delete": ("Delete", "Удалить"),
    "action.duplicate": ("Duplicate", "Дублировать"),
    "il.title": ("Input list", "Input list"),
    "il.unsaved": ("Not saved to a file yet (autosaved)", "Ещё не сохранён в файл (автосохранение включено)"),
    "il.new": ("New input list", "Новый input list"),
    "il.open": ("Open input list…", "Открыть input list…"),
    "il.save": ("Save input list", "Сохранить input list"),
    "il.saveAs": ("Save as…", "Сохранить как…"),
    "il.show": ("Show", "Шоу"),
    "il.artist": ("Artist", "Артист"),
    "il.event": ("Event", "Мероприятие"),
    "il.venue": ("Venue", "Площадка"),
    "il.date": ("Date", "Дата"),
    "il.engineer": ("Engineer", "Инженер"),
    "il.contact": ("Contact", "Контакт"),
    "il.notes": ("Notes", "Заметки"),
    "il.channels": ("Channels", "Каналы"),
    "il.count": ("%ld", "%ld"),
    "il.addChannel": ("Channel", "Канал"),
    "il.template": ("Template", "Шаблон"),
    "il.stereo": ("Make a stereo pair (L/R)", "Сделать стереопару (L/R)"),
    "il.moveUp": ("Move up", "Выше"),
    "il.moveDown": ("Move down", "Ниже"),
    "il.renumber": ("Renumber 1…N", "Перенумеровать 1…N"),
    "il.stagebox.fill": ("Stage box…", "Стейджбокс…"),
    "il.stagebox.prefix": ("Prefix", "Префикс"),
    "il.stagebox.start": ("Start: %ld", "Начать с: %ld"),
    "il.stagebox.onlyEmpty": ("Only empty fields", "Только пустые поля"),
    "il.stagebox.apply": ("Fill in", "Заполнить"),
    "il.col.source": ("Source", "Источник"),
    "il.col.mic": ("Mic / DI", "Микрофон / DI"),
    "il.col.stand": ("Stand", "Стойка"),
    "il.col.stagebox": ("Stage box", "Стейджбокс"),
    "il.col.insert": ("Insert", "Обработка"),
    "il.col.group": ("Group", "Группа"),
    "il.col.notes": ("Notes", "Примечание"),
    "il.empty": ("No channels yet — add one or pick a template", "Каналов пока нет — добавьте канал или выберите шаблон"),
    "il.issue.dupNumber": ("Channel %ld is used twice", "Канал %ld указан дважды"),
    "il.issue.dupStagebox": ("Stage box input %@ is used twice", "Вход стейджбокса %@ занят дважды"),
    "il.issue.emptySource": ("Channel %ld has no source", "У канала %ld не указан источник"),
    "il.issues.more": ("and %ld more", "и ещё %ld"),
    "il.mixes": ("Monitor mixes", "Мониторные миксы"),
    "il.addMix": ("Mix", "Микс"),
    "il.mix.name": ("Who / what", "Кому / что"),
    "il.mix.type": ("Type", "Тип"),
    "il.mix.stereo": ("Stereo", "Стерео"),
    "il.summary": ("Pull list", "Что выдать на сцену"),
    "il.sum.channels": ("channels", "каналов"),
    "il.sum.mixes": ("mixes", "миксов"),
    "il.sum.mics": ("Microphones and DI", "Микрофоны и DI"),
    "il.sum.stands": ("Stands", "Стойки"),
    "il.print.counts": ("%ld channels · %ld × +48V · %ld mixes", "%ld каналов · %ld × +48V · %ld миксов"),
    "il.stage": ("Stage plan", "Стейдж-план"),
    "il.export": ("Export", "Экспорт"),
    "il.export.pdf": ("Export PDF (input list + stage plan)", "Экспорт PDF (input list + сцена)"),
    "il.export.pngList": ("Export PNG — input list", "Экспорт PNG — input list"),
    "il.export.pngStage": ("Export PNG — stage plan", "Экспорт PNG — сцена"),
    "il.export.csvChannels": ("Export CSV — channels", "Экспорт CSV — каналы"),
    "il.export.csvMixes": ("Export CSV — mixes", "Экспорт CSV — миксы"),
    "stage.audience": ("AUDIENCE", "ЗРИТЕЛИ"),
    "stage.add.help": ("Add to the stage", "Добавить на сцену"),
    "stage.move": ("Move", "Переместить"),
    "stage.hint": ("Click a symbol above to add it, drag it on the stage, select it to edit. Arrow keys nudge, ⌫ deletes.", "Нажмите символ сверху, чтобы добавить; перетаскивайте по сцене; выделите, чтобы изменить. Стрелки — сдвиг, ⌫ — удалить."),
    "stage.label": ("Caption", "Подпись"),
    "stage.text": ("Text", "Текст"),
    "stage.text.default": ("Text", "Текст"),
    "stage.info": ("Channels / mix", "Каналы / микс"),
    "stage.rotation": ("Rotation: %.0f°", "Поворот: %.0f°"),
    "stage.fontSize": ("Text size: %.0f", "Размер текста: %.0f"),
    "stage.width": ("Width: %.1f m", "Ширина: %.1f м"),
    "stage.depth": ("Depth: %.1f m", "Глубина: %.1f м"),
    "stage.front": ("Bring to front", "На передний план"),
    "stage.back": ("Send to back", "На задний план"),
    "stage.size.width": ("Stage width: %.1f m", "Ширина сцены: %.1f м"),
    "stage.size.depth": ("Stage depth: %.1f m", "Глубина сцены: %.1f м"),
    "stage.snap": ("Snap to 25 cm", "Привязка 25 см"),
    "stage.kind.drumKit": ("Drum kit", "Ударные"),
    "stage.kind.percussion": ("Percussion", "Перкуссия"),
    "stage.kind.guitarAmp": ("Guitar amp", "Гитарный комбо"),
    "stage.kind.bassAmp": ("Bass amp", "Басовый комбо"),
    "stage.kind.keyboard": ("Keyboard", "Клавиши"),
    "stage.kind.piano": ("Grand piano", "Рояль"),
    "stage.kind.vocalMic": ("Vocal mic", "Вокальный мик."),
    "stage.kind.micStand": ("Mic stand", "Стойка"),
    "stage.kind.diBox": ("DI box", "DI"),
    "stage.kind.wedge": ("Wedge", "Монитор"),
    "stage.kind.iem": ("In-ear", "Ушной мон."),
    "stage.kind.sideFill": ("Side fill", "Сайдфил"),
    "stage.kind.speaker": ("Speaker", "Колонка"),
    "stage.kind.riser": ("Riser", "Подиум"),
    "stage.kind.person": ("Musician", "Музыкант"),
    "stage.kind.chair": ("Chair", "Стул"),
    "stage.kind.musicStand": ("Music stand", "Пюпитр"),
    "stage.kind.powerDrop": ("Power", "Питание 220 В"),
    "stage.kind.text": ("Text", "Текст"),
    "stand.none": ("—", "—"),
    "stand.tallBoom": ("Tall boom", "Высокий журавль"),
    "stand.shortBoom": ("Short boom", "Низкий журавль"),
    "stand.straight": ("Straight", "Прямая"),
    "stand.clip": ("Clip", "Клипса"),
    "stand.desk": ("Desk", "Настольная"),
    "stand.hanging": ("Hanging", "Подвес"),
    "chgroup.drums": ("Drums", "Ударные"),
    "chgroup.percussion": ("Percussion", "Перкуссия"),
    "chgroup.bass": ("Bass", "Бас"),
    "chgroup.guitar": ("Guitar", "Гитара"),
    "chgroup.keys": ("Keys", "Клавиши"),
    "chgroup.vocals": ("Vocals", "Вокал"),
    "chgroup.playback": ("Playback", "Фонограмма"),
    "chgroup.fx": ("FX / ambience", "Эффекты / зал"),
    "chgroup.other": ("Other", "Другое"),
    "mixtype.wedge": ("Wedge", "Монитор"),
    "mixtype.iem": ("In-ear", "Ушной"),
    "mixtype.sidefill": ("Side fill", "Сайдфил"),
    "mixtype.drumfill": ("Drum fill", "Драм-филл"),
    "mixtype.other": ("Other", "Другое"),
    "template.drums": ("Drum kit (10)", "Ударная установка (10)"),
    "template.drumsSmall": ("Drum kit, small (4)", "Ударные, минимум (4)"),
    "template.bass": ("Bass: DI + mic", "Бас: DI + микрофон"),
    "template.guitar": ("Electric guitar", "Электрогитара"),
    "template.acoustic": ("Acoustic guitar (DI)", "Акустическая гитара (DI)"),
    "template.keys": ("Keys stereo (DI)", "Клавиши стерео (DI)"),
    "template.leadVocal": ("Lead vocal", "Основной вокал"),
    "template.backingVocals": ("Backing vocals ×3", "Бэк-вокал ×3"),
    "template.playback": ("Playback stereo", "Фонограмма стерео"),
    "template.percussion": ("Percussion", "Перкуссия"),
    "template.ambience": ("Ambience L/R", "Зальные L/R"),
    "template.talkback": ("Talkback", "Толкбэк"),
    # Function #3 — show player
    "section.show": ("Qtrl", "Qtrl"),
    "show.new": ("New show", "Новое шоу"),
    "show.open": ("Open show…", "Открыть шоу…"),
    "show.save": ("Save show", "Сохранить шоу"),
    "show.name.placeholder": ("Show name", "Название шоу"),
    "show.next": ("Next", "Далее"),
    "show.endOfList": ("End of the list", "Конец списка"),
    "show.go.hint": ("Space", "Пробел"),
    "show.go.help": ("Start the cue on the playhead (Space)", "Запустить кью под курсором (Пробел)"),
    "show.pauseAll": ("Pause all", "Пауза"),
    "show.resumeAll": ("Resume", "Продолжить"),
    "show.panic": ("Stop all", "Стоп всё"),
    "show.panic.help": ("Esc: fade everything out; press again to cut at once", "Esc: плавно погасить всё; повторное нажатие — мгновенно"),
    "show.running": ("Playing", "Сейчас идёт"),
    "show.running.none": ("Nothing is playing", "Ничего не играет"),
    "show.outputs": ("Outputs", "Выходы"),
    "show.mode.edit": ("Edit", "Правка"),
    "show.mode.show": ("Show", "Шоу"),
    "show.mode.help": ("Show mode locks editing so nothing changes by accident", "Режим «Шоу» блокирует правку, чтобы ничего не изменить случайно"),
    "show.settings": ("Outputs and interface", "Выходы и звуковая карта"),
    "show.settings.hint": ("Each show output is patched to a channel of the interface. Several outputs can share a channel.",
                           "Каждый выход шоу назначается на канал звуковой карты. Несколько выходов могут идти в один канал."),
    "show.device.default": ("System output", "Системный выход"),
    "show.outputs.count": ("Show outputs: %d", "Выходов шоу: %d"),
    "show.channel": ("Channel %d", "Канал %d"),
    "show.panicFade": ("Stop all fade: %.1f s", "Затухание «Стоп всё»: %.1f с"),
    "show.goGuard": ("Double-GO guard: %.1f s", "Защита от двойного GO: %.1f с"),
    "show.output.error": ("Audio output unavailable", "Аудиовыход недоступен"),
    "show.memory.help": ("Audio loaded into memory", "Звук, загруженный в память"),
    "show.missing": ("%d missing", "Нет файлов: %d"),
    "show.relink": ("Find missing files…", "Найти пропавшие файлы…"),
    "show.relink.help": ("Choose a folder: files are found by name", "Выберите папку: файлы найдутся по имени"),
    "show.relink.done": ("Files relinked: %d", "Найдено файлов: %d"),
    "show.list": ("List", "Список"),
    "show.list.add": ("New cue list", "Новый список"),
    "show.list.rename": ("Rename list", "Переименовать список"),
    "show.addAudio": ("Add audio files…", "Добавить аудиофайлы…"),
    "show.addAudio.help": ("Add audio files (or drop them onto the list)", "Добавить аудиофайлы (или перетащите их в список)"),
    "show.addAudioToGroup": ("Add audio files to the group…", "Добавить аудиофайлы в группу…"),
    "show.add.media": ("Media", "Медиа"),
    "show.add.control": ("Control", "Управление"),
    "show.add.more": ("More…", "Ещё…"),
    "show.ungroup": ("Ungroup", "Разгруппировать"),
    "show.renumber": ("Renumber", "Перенумеровать"),
    "show.up": ("Move up", "Выше"),
    "show.down": ("Move down", "Ниже"),
    "show.move": ("Move cues", "Перемещение кью"),
    "show.check": ("Check show", "Проверка шоу"),
    "show.check.ok": ("Everything is ready", "Всё готово"),
    "show.issue.target": ("%@: no target", "%@: не выбрана цель"),
    "show.issue.file": ("%@: file not found", "%@: файл не найден"),
    "show.issue.number": ("Number %@ is used twice", "Номер %@ повторяется"),
    "show.issue.hotkey": ("Hotkey %@ is used twice", "Клавиша %@ назначена дважды"),
    "show.issue.emptyGroup": ("%@: empty group", "%@: пустая группа"),
    "show.issue.region": ("%@: end is before start", "%@: конец раньше начала"),
    "show.empty": ("Drop audio files here or use “+ Audio”.\nSpace = GO, Esc = stop all.",
                   "Перетащите сюда аудиофайлы или нажмите «+ Аудио».\nПробел — GO, Esc — стоп всё."),
    "show.col.number": ("No.", "№"),
    "show.col.name": ("Cue", "Кью"),
    "show.col.pre": ("Pre-wait", "До"),
    "show.tab.main": ("General", "Общее"),
    "show.tab.time": ("Time", "Время"),
    "show.tab.action": ("Action", "Действие"),
    "show.tab.outputs": ("Outputs", "Выходы"),
    "show.tab.pad": ("Pad", "Кнопка"),
    "show.pad.mode": ("When pressed", "При нажатии"),
    "show.pad.key": ("Key", "Клавиша"),
    "padmode.start": ("Start (ignore while playing)", "Запуск (повтор не мешает)"),
    "padmode.toggle": ("Start / stop", "Запуск / стоп"),
    "padmode.restart": ("Restart from the beginning", "Перезапуск с начала"),
    "padmode.hold": ("Play while held", "Играет, пока держишь"),
    "show.layout.simple": ("Simple", "Простой"),
    "show.layout.expert": ("Expert", "Эксперт"),
    "show.layout.help": ("Simple: list and one side panel. Expert: library, one-shot pads and timeline.",
                         "Простой: список и одна панель сбоку. Эксперт: библиотека, one-shot и таймлайн."),
    "show.lists": ("Cue lists", "Списки"),
    "show.banks": ("One-shot banks", "Банки one-shot"),
    "show.bank": ("Bank", "Банк"),
    "show.add.title": ("Add", "Добавить"),
    "show.oneShot": ("One-shot", "One-shot"),
    "show.pad.add": ("Add sounds to the bank…", "Добавить звуки в банк…"),
    "show.pad.empty": ("Drop sounds here.\nEach gets the next F-key.", "Перетащите сюда звуки.\nКаждый получит следующую клавишу F."),
    "show.timeline": ("Timeline", "Таймлайн"),
    "show.timeline.show": ("Whole show", "Всё шоу"),
    "show.timeline.group": ("Group %@", "Группа %@"),
    "show.timeline.dragHint": ("Drag a clip to change its pre-wait", "Перетащите клип, чтобы изменить паузу до"),
    "show.timeline.now": ("now", "сейчас"),
    "show.wave.title": ("Waveform", "Волна"),
    "show.wave.loading": ("Loading the file…", "Файл загружается…"),
    "show.wave.loop": ("Loop", "Петля"),
    "show.wave.play": ("Listen", "Слушать"),
    "show.wave.stop": ("Stop", "Стоп"),
    "show.wave.end": ("End", "Конец"),
    "show.wave.end.help": ("Listen to the last 3 seconds before the end", "Послушать последние 3 секунды до конца"),
    "show.wave.trim": ("Trim silence", "Обрезать тишину"),
    "show.wave.trim.help": ("Move start and end to where the sound begins and ends", "Поставить начало и конец туда, где звук начинается и заканчивается"),
    "show.wave.expand": ("Open a large editor", "Открыть большой редактор"),
    "show.wave.endField": ("End", "Конец"),
    "show.wave.noLoop": ("Once", "Один раз"),
    "show.wave.loopAll": ("Repeat all", "Повтор целиком"),
    "show.wave.loopPart": ("Loop inside", "Петля внутри"),
    "show.wave.times": ("%d times", "%d раз"),
    "show.wave.loopStart": ("Loop from", "Петля от"),
    "show.wave.loopEnd": ("Loop to", "Петля до"),
    "show.wave.loopPart.hint": ("The intro plays once, the blue part repeats, the rest plays after the last pass or a Devamp cue.",
                                "Начало звучит один раз, синяя часть повторяется, остаток — после последнего круга или кью «Выход из петли»."),
    "cue.kind.network": ("OSC", "OSC"),
    "error.show.noDevice": ("OSC cue without a device", "У OSC-кью не выбрано устройство"),
    "show.issue.device": ("%@: no OSC device", "%@: не выбрано OSC-устройство"),
    "osc.title": ("OSC devices", "OSC-устройства"),
    "osc.choose": ("What do you connect?", "Что подключаем?"),
    "osc.intro": ("OSC lets show cues control a video server, a lighting console or a mixer over the network. Add the device once — the guide shows what to switch on in it — then use OSC cues with ready-made commands.",
                  "OSC позволяет кью управлять видеосервером, световым или звуковым пультом по сети. Добавьте устройство один раз — мастер подскажет, что включить в нём, — и дальше используйте OSC-кью с готовыми командами."),
    "osc.none": ("No devices yet.", "Устройств пока нет."),
    "osc.add": ("Add device", "Добавить устройство"),
    "osc.edit": ("Edit", "Изменить"),
    "osc.monitor": ("OSC monitor", "OSC-монитор"),
    "osc.myip": ("Addresses of this Mac", "Адреса этого Mac"),
    "osc.noNetwork": ("No network connection", "Нет подключения к сети"),
    "osc.subnet.short": ("Other network", "Другая сеть"),
    "osc.subnet.warning": ("This address is not on the same network as this Mac. Messages will probably not arrive: connect both to the same switch / Wi-Fi and use addresses like 192.168.1.x on both.",
                           "Этот адрес не в одной сети с этим Mac — сообщения, скорее всего, не дойдут. Подключите оба к одному коммутатору / Wi-Fi и задайте адреса вида 192.168.1.x на обоих."),
    "osc.step.device": ("Switch on OSC in the device", "Включите OSC в устройстве"),
    "osc.step.address": ("Where it is", "Где оно находится"),
    "osc.step.test": ("Check the link", "Проверьте связь"),
    "osc.yourip": ("IP of this Mac (for answers): %@", "IP этого Mac (для ответов): %@"),
    "osc.name": ("Name", "Название"),
    "osc.host": ("IP address", "IP-адрес"),
    "osc.port": ("Port", "Порт"),
    "osc.prefix": ("Prefix", "Префикс"),
    "osc.thisMac": ("This Mac", "Этот Mac"),
    "osc.thisMac.help": ("The program runs on this same Mac", "Программа запущена на этом же Mac"),
    "osc.test": ("Check", "Проверить"),
    "osc.test.ok": ("The device answered", "Устройство ответило"),
    "osc.test.fail": ("No answer", "Нет ответа"),
    "osc.test.fail.hint": ("Check: the IP address and port; OSC is switched on in the device; both are on the same network; the macOS firewall allows SSMT (System Settings → Network → Firewall).",
                           "Проверьте: IP-адрес и порт; OSC включён в устройстве; оба в одной сети; брандмауэр macOS пропускает SSMT (Системные настройки → Сеть → Брандмауэр)."),
    "osc.test.udp": ("This device does not answer OSC, so the only check is to send a command and see it work.",
                     "Это устройство не отвечает по OSC, поэтому проверка одна: отправить команду и посмотреть, сработала ли она."),
    "osc.test.send": ("Send: %@", "Отправить: %@"),
    "osc.save.new": ("Add device", "Добавить устройство"),
    "osc.save": ("Save", "Сохранить"),
    "osc.monitor.hint": ("Shows OSC messages sent to this Mac. Point a device or an app (for example a TouchOSC button) at this Mac's IP and the port below, press something, and turn the message into a cue with one click.",
                         "Показывает OSC-сообщения, приходящие на этот Mac. Направьте устройство или приложение (например, кнопку TouchOSC) на IP этого Mac и порт ниже, нажмите что-нибудь — и превратите сообщение в кью одним кликом."),
    "osc.monitor.start": ("Listen", "Слушать"),
    "osc.monitor.stop": ("Stop", "Остановить"),
    "osc.monitor.on": ("Listening on port %d", "Слушаю порт %d"),
    "osc.monitor.clear": ("Clear", "Очистить"),
    "osc.monitor.makeCue": ("Make a cue", "Сделать кью"),
    "osc.cue.noDevices": ("Add the device this cue controls first (Resolume, a lighting console, a mixer…).",
                          "Сначала добавьте устройство, которым управляет кью (Resolume, световой пульт, микшер…)."),
    "osc.cue.device": ("Device", "Устройство"),
    "osc.cue.action": ("Command", "Команда"),
    "osc.cue.custom": ("Own address…", "Свой адрес…"),
    "osc.cue.address": ("OSC address", "OSC-адрес"),
    "osc.cue.args": ("Values", "Значения"),
    "osc.cue.args.hint": ("Separated by spaces: 1 (whole), 0.5 (fractional), \"text\", true / false.",
                          "Через пробел: 1 (целое), 0.5 (дробное), \"текст\", true / false."),
    "osc.cue.sendNow": ("Send now", "Отправить сейчас"),
    "osc.cue.devices": ("OSC devices…", "OSC-устройства…"),
    "osc.kind.resolume": ("Resolume", "Resolume"),
    "osc.kind.eos": ("ETC Eos", "ETC Eos"),
    "osc.kind.grandMA3": ("grandMA3", "grandMA3"),
    "osc.kind.magicQ": ("ChamSys MagicQ", "ChamSys MagicQ"),
    "osc.kind.x32": ("Behringer X32 / Midas M32", "Behringer X32 / Midas M32"),
    "osc.kind.qlab": ("QLab", "QLab"),
    "osc.kind.generic": ("Other device", "Другое устройство"),
    "osc.kind.resolume.hint": ("Arena / Avenue: clips, columns, layers", "Arena / Avenue: клипы, колонки, слои"),
    "osc.kind.eos.hint": ("Eos, Ion, Gio, Element, Nomad: cues, macros", "Eos, Ion, Gio, Element, Nomad: кью, макросы"),
    "osc.kind.grandMA3.hint": ("Any console command: sequences, cues", "Любая команда пульта: секвенции, кью"),
    "osc.kind.magicQ.hint": ("Playbacks: go, release", "Плейбеки: go, release"),
    "osc.kind.x32.hint": ("Channel mute and fader", "Мьют и фейдер каналов"),
    "osc.kind.qlab.hint": ("Another QLab: GO, start a cue", "Другой QLab: GO, запуск кью"),
    "osc.kind.generic.hint": ("Any OSC address (TouchDesigner, Millumin, MadMapper…)", "Любой OSC-адрес (TouchDesigner, Millumin, MadMapper…)"),
    "osc.howto.resolume": ("1. In Resolume open Preferences → OSC.\n2. Turn on OSC Input; leave the port 7000 (or type the same port here).\n3. Same Mac: press “This Mac”. Another computer: enter its IP (on that Mac: System Settings → Network).",
                           "1. В Resolume откройте Preferences → OSC.\n2. Включите OSC Input; порт оставьте 7000 (или впишите здесь тот же).\n3. Resolume на этом же Mac — нажмите «Этот Mac». На другом компьютере — впишите его IP (на том Mac: Системные настройки → Сеть)."),
    "osc.howto.eos": ("1. On the console: Setup → System Settings → Show Control → OSC.\n2. Turn on OSC RX, set OSC UDP RX Port = 8000.\n3. For the check: OSC TX on, OSC UDP TX IP = this Mac's IP (below), TX Port = 8001.\n4. Enter the console's IP here (Setup → Network on the console).",
                      "1. На пульте: Setup → System Settings → Show Control → OSC.\n2. Включите OSC RX, OSC UDP RX Port = 8000.\n3. Для проверки: включите OSC TX, OSC UDP TX IP = IP этого Mac (ниже), TX Port = 8001.\n4. Впишите здесь IP пульта (на пульте: Setup → Network)."),
    "osc.howto.grandMA3": ("1. On the console: Menu → In & Out → OSC.\n2. Add a line: Interface = the network port to the show network, Destination IP = this Mac's IP (below), Port = 8000, Prefix = gma3.\n3. Turn on Receive and Receive Command for the line, and Enable Input.\n4. Enter the console's IP here.",
                           "1. На пульте: Menu → In & Out → OSC.\n2. Добавьте строку: Interface — сетевой порт к сети шоу, Destination IP — IP этого Mac (ниже), Port = 8000, Prefix = gma3.\n3. Включите у строки Receive и Receive Command, а также Enable Input.\n4. Впишите здесь IP пульта."),
    "osc.howto.magicQ": ("1. On the console: Setup → View Settings → Network.\n2. OSC Mode = OSC Rx (or Tx and Rx), OSC Rx Port = 8000.\n3. Enter the console's IP here (Setup → View Settings → Network shows it).",
                         "1. На пульте: Setup → View Settings → Network.\n2. OSC Mode = OSC Rx (или Tx and Rx), OSC Rx Port = 8000.\n3. Впишите здесь IP пульта (он показан там же, в Network)."),
    "osc.howto.x32": ("1. Nothing to switch on: the console always listens for OSC on port 10023.\n2. Enter the console's IP (on the console: Setup → Network).\n3. The console and this Mac must be on the same network.",
                      "1. Включать ничего не нужно: пульт всегда слушает OSC на порту 10023.\n2. Впишите IP пульта (на пульте: Setup → Network).\n3. Пульт и этот Mac должны быть в одной сети."),
    "osc.howto.qlab": ("1. In QLab: Workspace Settings → Network (OSC Controls).\n2. Allow OSC control without a passcode, or set access for “no passcode”.\n3. Port 53000. Same Mac: “This Mac”; otherwise its IP.",
                       "1. В QLab: Workspace Settings → Network (OSC Controls).\n2. Разрешите управление по OSC без пароля (доступ для «no passcode»).\n3. Порт 53000. QLab на этом же Mac — «Этот Mac», иначе — его IP."),
    "osc.howto.generic": ("1. In the program or device, find the OSC settings and switch on OSC input.\n2. Note its IP and port and enter them here.\n3. In the cue, choose “Own address…” and type the address from its documentation, or catch it with the OSC monitor.",
                          "1. В программе или устройстве найдите настройки OSC и включите приём (OSC In / Input).\n2. Запишите IP и порт и впишите их здесь.\n3. В кью выберите «Свой адрес…» и впишите адрес из документации или поймайте его OSC-монитором."),
    "osc.find.resolume": ("Address of any button: in Resolume choose Shortcuts → Edit OSC and click the button.", "Адрес любой кнопки: в Resolume выберите Shortcuts → Edit OSC и нажмите на кнопку."),
    "osc.find.eos": ("Commands use the console's command line: “#” at the end means Enter.", "Команды — это командная строка пульта: «#» в конце означает Enter."),
    "osc.find.grandMA3": ("Any command you can type on the console works as text: Go+ Sequence 3, Off Executor 201…", "Сработает любая команда, которую можно набрать на пульте: Go+ Sequence 3, Off Executor 201…"),
    "osc.find.magicQ": ("Playback numbers are the playback faders on the current page.", "Номер плейбека — номер фейдера плейбека на текущей странице."),
    "osc.find.x32": ("Fader: 0 = −∞, 0.75 ≈ 0 dB, 1 = +10 dB.", "Фейдер: 0 = −∞, 0.75 ≈ 0 дБ, 1 = +10 дБ."),
    "osc.find.qlab": ("“Start a cue” takes the cue number as shown in QLab.", "«Запустить кью» — номер кью так, как он показан в QLab."),
    "osc.find.generic": ("Not sure of the address? Open the OSC monitor and send it from the device or its editor.", "Не знаете адрес? Откройте OSC-монитор и отправьте его из устройства или его редактора."),
    "osc.preset.resolume.clip": ("Launch a clip", "Запустить клип"),
    "osc.preset.resolume.column": ("Launch a column", "Запустить колонку"),
    "osc.preset.resolume.clear": ("Clear a layer", "Очистить слой"),
    "osc.preset.resolume.opacity": ("Layer opacity", "Прозрачность слоя"),
    "osc.preset.eos.cue": ("Fire a cue", "Запустить кью"),
    "osc.preset.eos.go": ("GO", "GO"),
    "osc.preset.eos.macro": ("Fire a macro", "Запустить макрос"),
    "osc.preset.eos.cmd": ("Command line", "Командная строка"),
    "osc.preset.ma3.go": ("Go+ sequence", "Go+ секвенции"),
    "osc.preset.ma3.cue": ("Go to a cue", "Перейти на кью"),
    "osc.preset.ma3.off": ("Sequence off", "Выключить секвенцию"),
    "osc.preset.ma3.cmd": ("Any command", "Любая команда"),
    "osc.preset.magicq.go": ("Playback GO", "GO плейбека"),
    "osc.preset.magicq.release": ("Release playback", "Снять плейбек"),
    "osc.preset.x32.mute": ("Mute a channel", "Выключить канал (мьют)"),
    "osc.preset.x32.unmute": ("Unmute a channel", "Включить канал"),
    "osc.preset.x32.fader": ("Channel fader", "Фейдер канала"),
    "osc.preset.qlab.go": ("GO", "GO"),
    "osc.preset.qlab.start": ("Start a cue", "Запустить кью"),
    "osc.field.layer": ("Layer", "Слой"),
    "osc.field.clip": ("Clip", "Клип"),
    "osc.field.column": ("Column", "Колонка"),
    "osc.field.value": ("Level", "Уровень"),
    "osc.field.list": ("Cue list", "Список кью"),
    "osc.field.cue": ("Cue", "Кью"),
    "osc.field.macro": ("Macro", "Макрос"),
    "osc.field.text": ("Command", "Команда"),
    "osc.field.sequence": ("Sequence", "Секвенция"),
    "osc.field.playback": ("Playback", "Плейбек"),
    "osc.field.channel": ("Channel", "Канал"),
    "qlab.menu": ("Import from QLab…", "Импорт из QLab…"),
    "qlab.title": ("Import from QLab", "Импорт из QLab"),
    "qlab.intro": ("Brings a QLab 4 / 5 show into Qtrl: cue lists, carts (as one-shot banks), cues with numbers, names, notes, colours, waits, continue modes, files, start / end, loops, fades and targets. The current show is replaced (⌘Z undoes); your audio interface, outputs and OSC devices stay.",
                   "Переносит шоу QLab 4 / 5 в Qtrl: списки, карты (как банки one-shot), кью с номерами, именами, заметками, цветами, паузами, режимами «затем», файлами, началом и концом, повторами, фейдами и целями. Текущее шоу заменяется (⌘Z отменит); звуковая карта, выходы и OSC-устройства остаются."),
    "qlab.live": ("From an open QLab — exact", "Из открытого QLab — точно"),
    "qlab.live.howto": ("Open the workspace in QLab (on this or another Mac in the network). In QLab: Workspace Settings → Network → allow OSC access (without a passcode, or type it here). Then press Connect.",
                        "Откройте проект в QLab (на этом или другом Mac в сети). В QLab: Workspace Settings → Network — разрешите доступ по OSC (без пароля или впишите пароль здесь). Затем нажмите «Подключиться»."),
    "qlab.passcode": ("Passcode (if set)", "Пароль (если есть)"),
    "qlab.connect": ("Connect", "Подключиться"),
    "qlab.workspace": ("Workspace", "Проект"),
    "qlab.import": ("Import", "Импортировать"),
    "qlab.noWorkspaces": ("QLab answered, but no workspace is open.", "QLab ответил, но открытых проектов нет."),
    "qlab.connectFailed": ("Could not reach QLab: check that it is running, the IP address, and that OSC access is allowed.",
                           "Не удалось связаться с QLab: проверьте, что он запущен, IP-адрес и что доступ по OSC разрешён."),
    "qlab.readFailed": ("QLab refused to give the cue lists: check the OSC access settings and the passcode.",
                        "QLab не отдал списки кью: проверьте настройки доступа по OSC и пароль."),
    "qlab.file": ("From a .qlab4 / .qlab5 file", "Из файла .qlab4 / .qlab5"),
    "qlab.file.hint": ("Without QLab. The file format is not published, so Qtrl takes what it recognises and lists what it could not. If something is missing, use the import from an open QLab.",
                       "Без QLab. Формат файла закрыт, поэтому Qtrl берёт то, что распознаёт, и показывает, что не получилось. Если чего-то не хватает — используйте импорт из открытого QLab."),
    "qlab.file.open": ("Choose a file…", "Выбрать файл…"),
    "qlab.file.unknown": ("Could not recognise this file. Open it in QLab and use the import from an open QLab — it is exact.",
                          "Не удалось распознать файл. Откройте его в QLab и используйте импорт из открытого QLab — он точный."),
    "qlab.done": ("Imported", "Импортировано"),
    "qlab.done.counts": ("Cues: %d (audio: %d) · lists: %d · one-shot banks: %d", "Кью: %d (аудио: %d) · списков: %d · банков one-shot: %d"),
    "qlab.unsupported": ("Not played by Qtrl yet — kept as memos with the QLab type in the notes:", "Qtrl пока не воспроизводит — оставлены заметками с типом QLab в примечании:"),
    "qlab.lostTargets": ("Cues whose target was not found: %d", "Кью, у которых не нашлась цель: %d"),
    "qlab.checkAfter": ("Check before the show: levels and routing are not taken from QLab (cues play at 0 dB on outputs 1–2), and fade target levels may need a look.",
                        "Проверьте перед шоу: уровни и маршрутизация из QLab не переносятся (кью играют на 0 дБ в выходы 1–2), целевые уровни фейдов стоит просмотреть."),
    "show.preWait": ("Pre-wait", "Пауза до"),
    "show.postWait": ("Post-wait", "Пауза после"),
    "show.col.action": ("Length", "Длина"),
    "show.col.post": ("Post-wait", "После"),
    "show.setPlayhead": ("Put playhead here", "Поставить курсор сюда"),
    "show.playNow": ("Play this cue now", "Запустить эту кью"),
    "show.stopCue": ("Stop this cue", "Остановить эту кью"),
    "show.fileMissing": ("File not found", "Файл не найден"),
    "show.noTarget": ("No target", "Цель не выбрана"),
    "show.inspector.none": ("Select a cue to edit it", "Выберите кью, чтобы настроить её"),
    "show.inspector.many": ("%d cues selected", "Выбрано кью: %d"),
    "show.notes": ("Notes", "Заметки"),
    "show.armed": ("Armed", "Активна"),
    "show.timing": ("Timing", "Время"),
    "show.continue": ("Then", "Затем"),
    "show.hotkey": ("Hotkey", "Клавиша"),
    "show.duration": ("Duration", "Длительность"),
    "show.sec": ("s", "с"),
    "show.file": ("File", "Файл"),
    "show.chooseFile": ("Choose…", "Выбрать…"),
    "show.start": ("Start", "Начало"),
    "show.end": ("End, s", "Конец, с"),
    "show.plays": ("Plays", "Повторы"),
    "show.rate": ("Speed", "Скорость"),
    "show.level": ("Level", "Уровень"),
    "show.fadeIn": ("Fade in", "Нарастание"),
    "show.fadeOut": ("Fade out", "Затухание"),
    "show.routing": ("Routing", "Маршрутизация"),
    "show.target": ("Target", "Цель"),
    "show.target.all": ("All cues", "Все кью"),
    "show.newTarget": ("New target", "Новая цель"),
    "show.curve": ("Curve", "Кривая"),
    "show.fade.changeLevel": ("Change level", "Менять уровень"),
    "show.fade.to": ("To level", "До уровня"),
    "show.fade.stop": ("Stop the target when done", "Остановить цель в конце"),
    "show.playlist.loop": ("Loop the playlist", "Повторять плейлист"),
    "show.playlist.shuffle": ("Shuffle", "Случайный порядок"),
    "show.group.count": ("Cues in the group: %d", "Кью в группе: %d"),
    "show.stopFade": ("Fade out", "Затухание"),
    "show.devamp.next": ("Then start the next cue", "Затем запустить следующую кью"),
    "error.show.missingFile": ("Audio file not found or unreadable", "Аудиофайл не найден или не читается"),
    "cue.kind.audio": ("Audio", "Аудио"),
    "cue.kind.fade": ("Fade", "Фейд"),
    "cue.kind.group": ("Group", "Группа"),
    "cue.kind.wait": ("Wait", "Пауза"),
    "cue.kind.memo": ("Memo", "Заметка"),
    "cue.kind.start": ("Start", "Старт"),
    "cue.kind.stop": ("Stop", "Стоп"),
    "cue.kind.pause": ("Pause", "Пауза кью"),
    "cue.kind.load": ("Load", "Загрузка"),
    "cue.kind.reset": ("Reset", "Сброс"),
    "cue.kind.goTo": ("Go to", "Перейти"),
    "cue.kind.target": ("Retarget", "Сменить цель"),
    "cue.kind.arm": ("Arm", "Включить"),
    "cue.kind.disarm": ("Disarm", "Выключить"),
    "cue.kind.devamp": ("Devamp", "Выход из петли"),
    "cue.help.start": ("Starts the target cue (or resumes it if paused).", "Запускает цель (или продолжает, если она на паузе)."),
    "cue.help.stop": ("Stops the target, or every cue when no target is set.", "Останавливает цель, а без цели — все кью."),
    "cue.help.pause": ("Pauses the target; GO or Start on it resumes.", "Ставит цель на паузу; GO или «Старт» продолжают."),
    "cue.help.load": ("Loads the target's audio into memory in advance.", "Заранее загружает звук цели в память."),
    "cue.help.reset": ("Stops the target at once.", "Мгновенно останавливает цель."),
    "cue.help.goTo": ("Moves the playhead to the target.", "Переносит курсор на цель."),
    "cue.help.target": ("Changes the target of another cue.", "Меняет цель другой кью."),
    "cue.help.arm": ("Re-enables the target.", "Снова включает цель."),
    "cue.help.disarm": ("Disables the target: it keeps its timing but does nothing.", "Выключает цель: её паузы остаются, действие — нет."),
    "cue.help.devamp": ("Lets a looping audio cue finish its current loop and end.", "Даёт зацикленному аудио доиграть текущий круг и закончиться."),
    "continue.none": ("Wait for GO", "Ждать GO"),
    "continue.autoContinue": ("Next cue after the post-wait", "Следующая кью после паузы"),
    "continue.autoFollow": ("Next cue when this one ends", "Следующая кью по окончании"),
    "group.mode.sequence": ("One after another (by their settings)", "По очереди (по их настройкам)"),
    "group.mode.simultaneous": ("All together", "Все вместе"),
    "group.mode.playlist": ("Playlist", "Плейлист"),
    "group.mode.random": ("One random cue", "Одна случайная кью"),
    "curve.sCurve": ("Smooth", "Плавная"),
    "curve.linearDB": ("Linear (dB)", "Линейная (дБ)"),
    "curve.linearGain": ("Linear (gain)", "Линейная (усиление)"),

}

DYNAMIC_PREFIXES = {
    "cue.kind.": [f"cue.kind.{k}" for k in ("audio", "fade", "group", "wait", "memo", "network", "start", "stop", "pause", "load", "reset", "goTo", "target", "arm", "disarm", "devamp")],
    "cue.help.": [f"cue.help.{k}" for k in ("start", "stop", "pause", "load", "reset", "goTo", "target", "arm", "disarm", "devamp")],
    "continue.": ["continue.none", "continue.autoContinue", "continue.autoFollow"],
    "group.mode.": [f"group.mode.{k}" for k in ("sequence", "simultaneous", "playlist", "random")],
    "curve.": ["curve.sCurve", "curve.linearDB", "curve.linearGain"],
    "osc.kind.": [f"osc.kind.{k}{s}" for k in ("resolume", "eos", "grandMA3", "magicQ", "x32", "qlab", "generic") for s in ("", ".hint")],
    "osc.howto.": [f"osc.howto.{k}" for k in ("resolume", "eos", "grandMA3", "magicQ", "x32", "qlab", "generic")],
    "osc.find.": [f"osc.find.{k}" for k in ("resolume", "eos", "grandMA3", "magicQ", "x32", "qlab", "generic")],
    "osc.preset.": [f"osc.preset.{k}" for k in ("resolume.clip", "resolume.column", "resolume.clear", "resolume.opacity", "eos.cue", "eos.go", "eos.macro", "eos.cmd", "ma3.go", "ma3.cue", "ma3.off", "ma3.cmd", "magicq.go", "magicq.release", "x32.mute", "x32.unmute", "x32.fader", "qlab.go", "qlab.start")],
    "osc.field.": [f"osc.field.{k}" for k in ("layer", "clip", "column", "value", "list", "cue", "macro", "text", "sequence", "playback", "channel")],
    "padmode.": [f"padmode.{k}" for k in ("start", "toggle", "restart", "hold")],
    "show.tab.": [f"show.tab.{k}" for k in ("main", "time", "action", "outputs", "pad")],
    "show.toggle.": ["show.pauseAll", "show.resumeAll", "error.show.missingFile", "error.show.noDevice"],
    "stage.kind.": [f"stage.kind.{k}" for k in ("drumKit", "percussion", "guitarAmp", "bassAmp", "keyboard", "piano", "vocalMic", "micStand", "diBox", "wedge", "iem", "sideFill", "speaker", "riser", "person", "chair", "musicStand", "powerDrop", "text")],
    "stand.": [f"stand.{k}" for k in ("none", "tallBoom", "shortBoom", "straight", "clip", "desk", "hanging")],
    "chgroup.": [f"chgroup.{k}" for k in ("drums", "percussion", "bass", "guitar", "keys", "vocals", "playback", "fx", "other")],
    "mixtype.": [f"mixtype.{k}" for k in ("wedge", "iem", "sidefill", "drumfill", "other")],
    "template.": [f"template.{k}" for k in ("drums", "drumsSmall", "bass", "guitar", "acoustic", "keys", "leadVocal", "backingVocals", "playback", "percussion", "ambience", "talkback")],
    "il.col.": [f"il.col.{k}" for k in ("source", "mic", "stand", "stagebox", "insert", "group", "notes")],
    "il.misc": ["il.open", "il.save", "stage.label", "stage.text"],
    "processor.source.": ["processor.source.behringer-x32", "processor.source.ah-sq", "processor.source.ah-dlive", "processor.source.midas-hd96", "processor.source.yamaha-cl", "processor.source.yamaha-tf", "processor.source.yamaha-rivage"],
    "error.": ["error.audioLost"],
    "eq.grid.": ["eq.grid.thirdOctave", "eq.grid.sixthOctave", "eq.grid.free"],
    "cal.section.": [f"cal.section.{k}" for k in ("measurement", "smallDiaphragm", "largeDiaphragm", "dynamic")],
    "stage.": [f"stage.{i}.{k}" for i in range(5) for k in ("title", "subtitle")],
    "graph.": ["graph.magnitude", "graph.phase", "graph.coherence"],
    "wizard.step.": [f"wizard.step.{i}" for i in range(10)],
    "target.": [f"target.{p}" for p in ("flat", "livePA", "speech", "club", "custom")],
    "capture.": [f"capture.{i}.{k}" for i in (1, 2, 3, 5) for k in ("title", "text", "short")],
    "reason.": ["reason.clipping", "reason.lowCoherence", "reason.tooFewAverages", "reason.streamDiscontinuity"],
    "verdict.": [f"verdict.{v}{t}" for v in ("excellent", "goodBut", "checkSettings") for t in ("", ".text")],
    "advice.": [f"advice.{a}" for a in ("polarityNotApplied", "delayNotApplied", "delayWrongSign", "levelMismatch", "conditionsChanged")],
}


def generate():
    catalog = {"sourceLanguage": "en", "version": "1.0", "strings": {}}
    for key in sorted(STRINGS):
        en, ru = STRINGS[key]
        catalog["strings"][key] = {
            "extractionState": "manual",
            "localizations": {
                "en": {"stringUnit": {"state": "translated", "value": en}},
                "ru": {"stringUnit": {"state": "translated", "value": ru}},
            },
        }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(catalog, f, ensure_ascii=False, indent=2)
        f.write("\n")


def check():
    used = set()
    for dirpath, _, files in os.walk(os.path.join(ROOT, "App")):
        for name in files:
            if name.endswith(".swift"):
                text = open(os.path.join(dirpath, name), encoding="utf-8").read()
                used |= set(re.findall(r'\.t\("([a-z0-9.]+)"', text))
                used |= set(re.findall(r'"((?:noise|ref|graph)\.[a-z.]+)"', text))
    missing = sorted(k for k in used if k not in STRINGS and not k.endswith("."))
    for keys in DYNAMIC_PREFIXES.values():
        missing += [k for k in keys if k not in STRINGS]
    generated = json.load(open(OUT, encoding="utf-8"))
    stale = sorted(set(STRINGS) ^ set(generated["strings"]))
    if missing or stale:
        print("Missing keys:", missing)
        print("Catalog out of date:", stale)
        sys.exit(1)
    print(f"OK: {len(used)} keys used, {len(STRINGS)} defined")


if __name__ == "__main__":
    {"generate": generate, "check": check}[sys.argv[1] if len(sys.argv) > 1 else "check"]()
