#!/usr/bin/env python3
"""Source of truth for UI strings (en, ru). Generates App/SSMT/Resources/Localizable.xcstrings
and verifies that every key used in Swift sources exists.

Usage: scripts/strings.py generate | check
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "App/SSMT/Resources/Localizable.xcstrings")

STRINGS = {
    "app.title": ("SSMT · SYSTEM SETUP", "SSMT · НАСТРОЙКА СИСТЕМЫ"),
    "app.subtitle": ("SoundSolution Multi Tool", "SoundSolution Multi Tool"),
    "action.stop": ("STOP", "STOP"),
    "action.stop.help": ("Mute the test signal immediately (Esc)", "Мгновенно заглушить тестовый сигнал (Esc)"),
    "noise.start": ("Start noise", "Включить шум"),
    "noise.on": ("Noise on", "Шум включён"),
    "noise.toggle": ("Noise on/off", "Шум вкл/выкл"),
    "noise.pink": ("Pink noise (random)", "Розовый шум (случайный)"),
    "noise.white": ("White noise", "Белый шум"),
    "noise.periodic": ("Periodic pink (fast)", "Периодический розовый (быстрый)"),
    "noise.periodic.hint": ("Fast mode: coherence is not meaningful with periodic noise.",
                            "Быстрый режим: с периодическим шумом когерентность не имеет смысла."),
    "engine.running": ("Running", "Работает"),
    "engine.stopped": ("Stopped", "Остановлено"),
    "engine.dropouts": ("Dropouts", "Пропуски"),
    "engine.start": ("Start audio", "Запустить аудио"),
    "engine.stop": ("Stop audio", "Остановить аудио"),
    "delay.find": ("Find delay", "Найти задержку"),
    "delay.searching": ("Searching…", "Поиск…"),
    "delay.locked": ("DELAY LOCKED", "ЗАДЕРЖКА ЗАФИКСИРОВАНА"),
    "delay.unreliable": ("Delay not found reliably. Raise the level or check the microphone.",
                         "Задержка найдена ненадёжно. Поднимите уровень или проверьте микрофон."),
    "setup.source": ("Source", "Источник"),
    "setup.interface": ("Interface", "Интерфейс"),
    "setup.simulation": ("Simulation (virtual room)", "Симуляция (виртуальный зал)"),
    "setup.mic.channel": ("Microphone input", "Вход микрофона"),
    "setup.output.channel": ("Signal output", "Выход сигнала"),
    "setup.ref.channel": ("Reference input", "Вход референса"),
    "setup.no48k": ("Device does not support 48 kHz", "Устройство не поддерживает 48 кГц"),
    "setup.reference": ("Reference", "Референс"),
    "setup.temperature": ("Air temperature", "Температура воздуха"),
    "setup.refresh": ("Refresh device list", "Обновить список устройств"),
    "setup.generator": ("Generator", "Генератор"),
    "setup.noise": ("Signal", "Сигнал"),
    "setup.level": ("Level", "Уровень"),
    "setup.max.level": ("Maximum level", "Максимальный уровень"),
    "setup.output.level": ("Output now", "Выход сейчас"),
    "ref.internal": ("Internal (no cable)", "Внутренний (без кабеля)"),
    "ref.loopback": ("Loopback cable", "Кабель loopback"),
    "ref.internal.hint": ("The generated signal is the reference. Only the microphone and one output are needed.",
                          "Референс — сам генерируемый сигнал. Нужны только микрофон и один выход."),
    "ref.loopback.hint": ("Connect a cable from the signal output to the reference input.",
                          "Соедините кабелем выход сигнала со входом референса."),
    "safety.hf.warning": ("High noise levels can damage HF drivers. Raise the level gradually.",
                          "Высокий уровень шума может повредить ВЧ-драйверы. Поднимайте уровень постепенно."),
    "permission.denied": ("Microphone access denied. Allow SSMT in System Settings → Privacy & Security → Microphone.",
                          "Нет доступа к микрофону. Разрешите SSMT в Системных настройках → Конфиденциальность и безопасность → Микрофон."),
    "sim.title": ("Virtual system", "Виртуальная система"),
    "sim.hint": ("Simulates muting groups on the processor.", "Имитирует мьют групп на процессоре."),
    "sim.sub": ("Subwoofers on", "Сабвуферы включены"),
    "sim.main": ("Mains (satellites) on", "Сателлиты включены"),
    "display.title": ("Display", "Отображение"),
    "display.smoothing": ("Smoothing", "Сглаживание"),
    "display.smoothing.none": ("None", "Нет"),
    "display.coherence.threshold": ("Coherence threshold", "Порог когерентности"),
    "display.reset.avg": ("Reset averages", "Сбросить усреднение"),
    "display.reset.clip": ("Reset clip", "Сбросить клиппинг"),
    "settings.language": ("Language", "Язык"),
    "language.system": ("System", "Системный"),
    "meters.title": ("Inputs", "Входы"),
    "meters.mic": ("Microphone", "Микрофон"),
    "meters.ref": ("Reference", "Референс"),
    "meters.clip": ("CLIP", "КЛИП"),
    "meters.coherence": ("Coherence", "Когерентность"),
    "meters.averages": ("Averages", "Усреднений"),
    "meters.delay": ("Delay", "Задержка"),
    "quality.good": ("Good", "Хорошо"),
    "quality.weak": ("Weak", "Слабо"),
    "quality.repeat": ("Repeat", "Повторить"),
    "quality.none": ("No data", "Нет данных"),
    "graphs.title": ("Transfer function", "Передаточная функция"),
    "graphs.empty": ("Start the audio and the noise to see the measurement.",
                     "Запустите аудио и шум, чтобы увидеть измерение."),
    "graph.magnitude": ("Magnitude", "АЧХ"),
    "graph.phase": ("Phase", "Фаза"),
    "graph.coherence": ("Coherence", "Когерентность"),
    "action.cancel": ("Cancel", "Отмена"),
    "setup.split": ("Separate input and output devices", "Разные устройства для входа и выхода"),
    "setup.split.hint": ("SSMT creates a private aggregate device with drift correction so both run on one clock.",
                         "SSMT создаст частное агрегатное устройство с коррекцией дрейфа, чтобы вход и выход работали от одних часов."),
    "setup.input.device": ("Microphone device", "Устройство микрофона"),
    "setup.output.device": ("Output device", "Устройство выхода"),
    "autolevel.run": ("Auto level", "Автоуровень"),
    "autolevel.help": ("Measures room noise, then raises the level until SNR ≥ 20 dB or the maximum level.",
                       "Замеряет шум помещения, затем поднимает уровень до SNR ≥ 20 dB или до максимального уровня."),
    "autolevel.noise": ("Measuring room noise — keep quiet…", "Замер шума помещения — тишина…"),
    "autolevel.raising": ("Raising level…", "Поднимаю уровень…"),
    "autolevel.ok": ("Level %.0f dBFS · SNR %.0f dB", "Уровень %.0f dBFS · SNR %.0f dB"),
    "autolevel.max": ("Maximum reached · SNR only %.0f dB", "Достигнут максимум · SNR только %.0f dB"),
    "autolevel.clipped": ("Clipping — level reduced", "Клиппинг — уровень снижен"),
    "cal.title": ("Calibration", "Калибровка"),
    "cal.mic": ("Microphone", "Микрофон"),
    "cal.mic.none": ("None", "Нет"),
    "cal.mic.uncalibrated": ("Microphone not calibrated", "Микрофон не откалиброван"),
    "cal.points": ("%ld points", "%ld точек"),
    "cal.remove": ("Remove from library", "Удалить из библиотеки"),
    "cal.import": ("Import calibration file…", "Импорт файла калибровки…"),
    "cal.spl": ("SPL calibration", "Калибровка SPL"),
    "cal.spl.none": ("SPL not calibrated", "SPL не откалиброван"),
    "cal.apply": ("Apply", "Применить"),
    "cal.calibrator": ("Read calibrator", "Считать калибратор"),
    "cal.calibrator.help": ("Put the calibrator on the microphone; the test signal is switched off.",
                            "Наденьте калибратор на микрофон; тестовый сигнал будет выключен."),
    "spl.reset": ("Reset SPL", "Сбросить SPL"),
    "mode.wizard": ("Wizard", "Мастер"),
    "mode.expert": ("Expert", "Эксперт"),
    "mode.stage": ("Stage", "Сцена"),
    "mode.stage.help": ("Large, high-contrast numbers readable from a distance", "Крупные контрастные цифры, читаемые издалека"),
    "wizard.step.0": ("Prepare", "Подготовка"),
    "wizard.step.1": ("System", "Система"),
    "wizard.step.2": ("Subs", "Сабы"),
    "wizard.step.3": ("Mains", "Топы"),
    "wizard.step.4": ("Tune", "Тюнер"),
    "wizard.step.5": ("Verify", "Проверка"),
    "wizard.step.6": ("Zone", "Зона"),
    "wizard.step.7": ("EQ", "EQ"),
    "wizard.step.8": ("EQ check", "Проверка EQ"),
    "wizard.step.9": ("Done", "Готово"),
    "wizard.begin": ("Start setup", "Начать настройку"),
    "wizard.back": ("Back", "Назад"),
    "wizard.restart": ("New setup", "Новая настройка"),
    "wizard.next.eq": ("Next: EQ over the listening area", "Далее: EQ по зоне прослушивания"),
    "prep.title": ("Prepare the measurement", "Подготовка к замеру"),
    "prep.text": ("Place the measurement microphone at the main listening position, pointing at the system. Go through the checklist.",
                  "Поставьте измерительный микрофон в основную точку прослушивания, направив на систему. Пройдите список проверки."),
    "prep.checklist": ("Checklist", "Список проверки"),
    "prep.audio": ("Audio interface", "Звуковая карта"),
    "prep.audio.hint": ("Choose the interface on the left and start the audio.", "Выберите карту слева и запустите аудио."),
    "prep.mic": ("Microphone signal", "Сигнал микрофона"),
    "prep.mic.ok": ("Signal present, no clipping.", "Сигнал есть, клиппинга нет."),
    "prep.mic.clip": ("Clipping! Turn the microphone preamp down.", "Клиппинг! Уменьшите усиление микрофонного входа."),
    "prep.mic.hint": ("No signal from the microphone — check phantom power and the input.",
                      "Нет сигнала с микрофона — проверьте фантомное питание и вход."),
    "prep.level": ("Room noise and level", "Шум помещения и уровень"),
    "prep.level.hint": ("Keep quiet for 5 s, then the noise rises slowly to a safe working level.",
                        "5 с тишины, затем шум плавно поднимется до безопасного рабочего уровня."),
    "prep.delay": ("System delay", "Задержка системы"),
    "prep.delay.hint": ("All loudspeakers on. The delay is found once and locked for the whole setup.",
                        "Все громкоговорители включены. Задержка находится один раз и фиксируется на всю настройку."),
    "prep.system": ("Your system", "Ваша система"),
    "prep.hasSub": ("The system has subwoofers", "В системе есть сабвуферы"),
    "prep.knownCrossover": ("I know the crossover frequency", "Я знаю частоту раздела"),
    "prep.crossover.auto": ("Detected automatically", "Определится автоматически"),
    "prep.delayStep": ("Processor delay step", "Шаг задержки процессора"),
    "prep.levelStep": ("Processor level step", "Шаг уровня процессора"),
    "prep.fastMode": ("Fast mode (skip the mains-only capture)", "Быстрый режим (без замера «только топы»)"),
    "prep.fastMode.warning": ("Fast mode derives the mains from \"whole system − subs\". Less accurate near dips; nothing in the system may change between captures.",
                              "Быстрый режим вычисляет топы как «вся система − сабы». Менее точно около провалов; между замерами в системе ничего не должно меняться."),
    "prep.notReady": ("Start the audio and lock the delay to continue.", "Чтобы продолжить, запустите аудио и зафиксируйте задержку."),
    "capture.1.title": ("Whole system", "Вся система"),
    "capture.1.text": ("Turn ON all loudspeakers: subwoofers and mains. This is the \"before\" reference.",
                       "Включите ВСЕ громкоговорители: сабвуферы и топы. Это контрольный замер «до»."),
    "capture.2.title": ("Subwoofers only", "Только сабвуферы"),
    "capture.2.text": ("Mute the mains (satellites) on the processor. Leave only the subwoofers on.",
                       "Замьютьте сателлиты (топы) на процессоре. Оставьте включёнными только сабвуферы."),
    "capture.3.title": ("Mains only", "Только топы"),
    "capture.3.text": ("Unmute the mains and mute the subwoofers.", "Включите сателлиты и замьютьте сабвуферы."),
    "capture.5.title": ("Verification", "Проверочный замер"),
    "capture.5.text": ("Enter the settings on the processor, turn ON all loudspeakers and capture again.",
                       "Введите настройки в процессор, включите ВСЕ громкоговорители и сделайте замер."),
    "capture.start": ("Capture", "Замер"),
    "capture.repeat": ("Repeat capture", "Повторить замер"),
    "capture.progress": ("Capture", "Замер"),
    "capture.accepted": ("Capture accepted", "Замер принят"),
    "capture.acceptedWeak": ("Accepted, but the signal was weak", "Принят, но сигнал был слабым"),
    "capture.rejected": ("Capture not accepted:", "Замер не принят:"),
    "capture.streamRestarted": ("The audio stream restarted — the delay must be found again and the captures repeated.",
                                "Аудиопоток перезапустился — нужно заново найти задержку и повторить замеры."),
    "reason.clipping": ("clipping at the microphone input.", "клиппинг на входе микрофона."),
    "reason.lowCoherence": ("the measurement is unstable (noise, wind, people talking, or the group is not on).",
                            "измерение нестабильно (шум, ветер, разговоры или нужная группа не включена)."),
    "reason.tooFewAverages": ("too short.", "слишком короткий."),
    "reason.streamDiscontinuity": ("audio dropout during the capture.", "пропуск аудио во время замера."),
    "group.subs": ("Subwoofers", "Сабвуферы"),
    "group.mains": ("Mains (satellites)", "Сателлиты (топы)"),
    "group.on": ("ON", "ВКЛ"),
    "group.muted": ("MUTED", "МЬЮТ"),
    "sim.doIt": ("Simulation: do it for me", "Симуляция: сделать за меня"),
    "sim.applySettings": ("Simulation: enter the settings on the virtual processor", "Симуляция: ввести настройки в виртуальный процессор"),
    "results.title": ("Tune by the needle", "Настройте по стрелке"),
    "results.text": ("The cards show the target. Turn the knobs on your processor while watching the needles — like a guitar tuner — until everything is green.",
                     "Карточки — это цель. Крутите ручки процессора, глядя на стрелки, как в гитарном тюнере, пока всё не станет зелёным."),
    "results.failed": ("Could not compute the alignment. Repeat the captures (louder, or another microphone position).",
                       "Не удалось рассчитать выравнивание. Повторите замеры (громче или с другой позиции микрофона)."),
    "results.ambiguous": ("The solution is ambiguous: another setting sums almost as well. Better: repeat the captures from another microphone position.",
                          "Решение неоднозначно: другая настройка складывается почти так же. Лучше повторить замеры с другой позиции микрофона."),
    "results.alternatives": ("Alternatives:", "Альтернативы:"),
    "results.fastMode": ("Fast mode: reduced accuracy.", "Быстрый режим: точность понижена."),
    "results.prediction": ("Expected result", "Ожидаемый результат"),
    "results.applied": ("I entered the settings → verify", "Я ввёл настройки → проверка"),
    "card.delay.sub": ("Subwoofer delay", "Задержка сабвуфера"),
    "card.delay.mains": ("Mains delay", "Задержка топов"),
    "card.delay.sub.detail": ("Add to the subwoofer output (≈ %.2f m).", "Добавьте на выход сабвуфера (≈ %.2f м)."),
    "card.delay.mains.detail": ("The subwoofers arrive late: delay the mains (≈ %.2f m). Fills and delays shift with them.",
                                "Сабвуферы приходят позже: задержите топы (≈ %.2f м). Филлы и делеи сместятся вместе с ними."),
    "card.delay.none.detail": ("The delay is already correct.", "Задержка уже правильная."),
    "card.polarity": ("Subwoofer polarity", "Полярность сабвуфера"),
    "polarity.normal": ("Normal", "Прямая"),
    "polarity.invert": ("Invert", "Инвертировать"),
    "card.polarity.normal.detail": ("Leave the polarity as it is.", "Оставьте полярность как есть."),
    "card.polarity.invert.detail": ("Switch the subwoofer polarity (phase 180°).", "Переключите полярность сабвуфера (фаза 180°)."),
    "card.level": ("Subwoofer level", "Уровень сабвуфера"),
    "card.level.detail": ("Change relative to the current setting. The overall tonal balance is refined by EQ.",
                          "Изменение относительно текущего. Общий тональный баланс уточнит EQ."),
    "curve.before": ("Before", "До"),
    "curve.prediction": ("Prediction", "Прогноз"),
    "curve.after": ("After", "После"),
    "verdict.excellent": ("Excellent", "Отлично"),
    "verdict.excellent.text": ("The subwoofers and mains now add up in the crossover region.", "Сабвуферы и топы теперь складываются в зоне раздела."),
    "verdict.goodBut": ("Good, but…", "Хорошо, но…"),
    "verdict.goodBut.text": ("Summation improved, but not as much as predicted.", "Сложение улучшилось, но меньше, чем ожидалось."),
    "verdict.checkSettings": ("Check polarity and delay", "Проверьте полярность и задержку"),
    "verdict.checkSettings.text": ("The result does not match the prediction.", "Результат не совпадает с прогнозом."),
    "verify.dip": ("Crossover dip", "Провал на кроссовере"),
    "verify.sum": ("Summation", "Сложение"),
    "verify.predictionError": ("Deviation from prediction", "Отклонение от прогноза"),
    "verify.curves": ("Before / prediction / after", "До / прогноз / после"),
    "verify.again": ("Repeat verification", "Повторить проверку"),
    "advice.polarityNotApplied": ("Looks like the polarity was not changed. Check the subwoofer polarity on the processor.",
                                  "Похоже, полярность не изменена. Проверьте полярность сабвуфера в процессоре."),
    "advice.delayNotApplied": ("Looks like the delay was not entered. Check the delay on the processor.",
                               "Похоже, задержка не введена. Проверьте задержку в процессоре."),
    "advice.delayWrongSign": ("The delay seems to be on the wrong group (subs vs mains).", "Похоже, задержка введена не той группе (сабы ↔ топы)."),
    "advice.levelMismatch": ("The level change seems not to be applied.", "Похоже, изменение уровня не применено."),
    "advice.conditionsChanged": ("Something changed since the captures (microphone position, processor settings, people in the room). Repeat the setup.",
                                 "С момента замеров что-то изменилось (позиция микрофона, настройки процессора, люди в зале). Повторите настройку."),
    "finished.title": ("Setup complete", "Настройка завершена"),
    "finished.text": ("Settings for the processor and the result in numbers. Export the filters or start a new setup.",
                      "Настройки для процессора и результат в цифрах. Экспортируйте фильтры или начните новую настройку."),
    "tuner.title": ("Live tuner", "Тюнер"),
    "tuner.stage.sub": ("Subwoofer: polarity, level and delay", "Сабвуфер: полярность, уровень и задержка"),
    "tuner.stage.mains": ("Mains delay", "Задержка топов"),
    "tuner.hint": ("All loudspeakers on, noise running. The needle follows your changes within 1–2 seconds; wait for it to settle.",
                   "Все громкоговорители включены, шум идёт. Стрелка реагирует на изменения за 1–2 секунды — дождитесь, пока она успокоится."),
    "tuner.waiting": ("Listening…", "Слушаю…"),
    "tuner.unreliable": ("Unstable signal", "Сигнал нестабилен"),
    "tuner.inTune": ("IN TUNE", "В СТРОЮ"),
    "tuner.less": ("less", "меньше"),
    "tuner.more": ("more", "больше"),
    "tuner.quieter": ("quieter", "тише"),
    "tuner.louder": ("louder", "громче"),
    "tuner.sub.more": ("Add subwoofer delay", "Добавьте задержку сабвуферу"),
    "tuner.sub.less": ("Reduce subwoofer delay", "Уменьшите задержку сабвуфера"),
    "tuner.mains.more": ("Add mains delay", "Добавьте задержку топам"),
    "tuner.mains.less": ("Reduce mains delay", "Уменьшите задержку топов"),
    "tuner.level.up": ("Turn the subwoofer up", "Прибавьте уровень сабвуфера"),
    "tuner.level.down": ("Turn the subwoofer down", "Убавьте уровень сабвуфера"),
    "tuner.polarity.switch": ("Switch polarity", "Переключите полярность"),
    "tuner.polarity.ok": ("Correct", "Верно"),
    "tuner.mainsLater": ("The subwoofers arrive late: the mains delay is tuned in the next step.",
                         "Сабвуферы приходят позже: задержку топов настроим следующим шагом."),
    "tuner.next.mains": ("Subwoofer done → mains delay", "Сабвуфер готов → задержка топов"),
    "tuner.verify.ready": ("All in tune → verify", "Всё в строю → проверка"),
    "tuner.scale": ("Full scale = a quarter period at the crossover (%.2f ms)", "Вся шкала = четверть периода на частоте раздела (%.2f мс)"),
    "vproc.title": ("Virtual processor", "Виртуальный процессор"),
    "vproc.hint": ("Simulation: these are the knobs of the virtual loudspeaker processor. Turn them and watch the needles.",
                   "Симуляция: это ручки виртуального процессора. Крутите их и смотрите на стрелки."),
    "vproc.subDelay": ("Sub delay", "Задержка саба"),
    "vproc.mainsDelay": ("Mains delay", "Задержка топов"),
    "vproc.subLevel": ("Sub level", "Уровень саба"),
    "vproc.subPolarity": ("Sub polarity inverted", "Полярность саба инвертирована"),
    "unit.ms": ("ms", "мс"),
    "gauge.quality": ("Signal quality", "Качество сигнала"),
    "gauge.quality.good": ("Good — ready to measure", "Хорошо — можно мерить"),
    "gauge.quality.weak": ("Weak — quieter room or louder signal", "Слабо — тише в зале или громче сигнал"),
    "gauge.quality.bad": ("Bad — check the group is on and the room is quiet", "Плохо — проверьте, что группа включена и в зале тихо"),
    "gauge.quality.clip": ("Clipping — turn the mic preamp down", "Клиппинг — уменьшите усиление микрофона"),
    "gauge.snr": ("Signal / noise", "Сигнал / шум"),
    "gauge.snr.good": ("Enough above the room noise", "Достаточно выше шума зала"),
    "gauge.snr.low": ("Too close to the room noise — raise the level", "Слишком близко к шуму зала — поднимите уровень"),
    "gauge.snr.needNoise": ("Run auto level first", "Сначала запустите автоуровень"),
    "gauge.deviation": ("Deviation from target", "Отклонение от цели"),
    "gauge.score": ("Quality score", "Оценка качества"),
    "gauge.score.note": ("The score is a guide, not a guarantee.", "Оценка — ориентир, а не гарантия."),
    "gauge.before": ("before: %.1f dB", "было: %.1f dB"),
    "gauge.beforeScore": ("before: %ld", "было: %ld"),
    "gauge.matches": ("Matches the prediction", "Совпадает с прогнозом"),
    "gauge.differs": ("Differs from the prediction", "Отличается от прогноза"),
    "capture.ready": ("Wait for the needle to turn green, then press Capture.", "Дождитесь зелёной стрелки и нажмите «Замер»."),
    "capture.running": ("Measuring — keep quiet, don't move the microphone.", "Идёт замер — тишина, микрофон не двигать."),
    "tuner.cut": ("cut", "срез"),
    "tuner.boost": ("boost", "подъём"),
    "eq.points.title": ("Measure the listening area", "Замер по зоне прослушивания"),
    "eq.verify.title": ("Check the EQ over the area", "Проверка EQ по зоне"),
    "eq.points.text": ("Put the microphone at point %ld of %ld (see the map), at ear height. Wait for the green needle and capture.",
                       "Поставьте микрофон в точку %ld из %ld (см. схему) на высоте ушей. Дождитесь зелёной стрелки и сделайте замер."),
    "eq.point.rejected": ("Point not accepted:", "Точка не принята:"),
    "eq.capturePoint": ("Capture point %ld", "Замер точки %ld"),
    "eq.compute": ("Calculate EQ", "Рассчитать EQ"),
    "eq.iterate": ("One more correction round", "Ещё одна итерация коррекции"),
    "eq.finish": ("Finish", "Завершить"),
    "eq.iterationLimit": ("Two correction rounds done — better stop here and not over-tweak the system.",
                          "Две итерации коррекции сделаны — лучше остановиться и не «закручивать» систему."),
    "eq.target": ("Target curve", "Целевая кривая"),
    "eq.pointCount": ("Points: %ld", "Точек: %ld"),
    "eq.map": ("Measurement points", "Точки замера"),
    "eq.map.stage": ("STAGE", "СЦЕНА"),
    "target.flat": ("Flat", "Плоская"),
    "target.livePA": ("Live / PA", "Живой звук / PA"),
    "target.speech": ("Speech", "Речь"),
    "target.club": ("Club", "Клуб"),
    "eq.tune.title": ("Enter the EQ by the needles", "Введите EQ по стрелкам"),
    "eq.tune.text": ("Leave the microphone at point 1. Start the tuner, then enter the bands one by one on the processor: the needle shows how many dB are still missing.",
                     "Оставьте микрофон в точке 1. Запустите тюнер и вводите полосы по одной в процессор: стрелка показывает, сколько dB ещё не хватает."),
    "eq.tune.reference": ("Nothing entered yet? The tuner first listens for 6 s to remember the starting point.",
                          "Ещё ничего не введено? Тюнер сначала 6 с слушает, чтобы запомнить исходное состояние."),
    "eq.tune.start": ("Start EQ tuner", "Запустить тюнер EQ"),
    "eq.tune.entered": ("Bands entered → check over the area", "Полосы введены → проверка по зоне"),
    "eq.tune.allSet": ("All in tune → check over the area", "Всё в строю → проверка по зоне"),
    "eq.nothingToDo": ("The response is already close to the target — no EQ needed.", "АЧХ уже близка к цели — EQ не нужен."),
    "eq.notCorrectable": ("Some areas are not corrected on purpose: narrow dips and big differences between points are room acoustics, not the system's response.",
                          "Некоторые участки специально не корректируются: узкие провалы и большой разброс между точками — это акустика зала, а не АЧХ системы."),
    "eq.bands": ("EQ bands", "Полосы EQ"),
    "eq.band.title": ("Band %ld · %.0f Hz", "Полоса %ld · %.0f Гц"),
    "eq.band.cutMore": ("Cut %.1f dB more", "Убавьте ещё %.1f dB"),
    "eq.band.boostMore": ("Add %.1f dB", "Прибавьте %.1f dB"),
    "eq.band.shape": ("Gain is right — check frequency and Q", "Усиление верное — проверьте частоту и Q"),
    "eq.overall": ("EQ vs plan", "EQ против плана"),
    "eq.overall.hint": ("Keep entering the bands", "Продолжайте вводить полосы"),
    "eq.curves": ("EQ: plan and entered", "EQ: план и введено"),
    "curve.plan": ("Plan", "План"),
    "curve.entered": ("Entered", "Введено"),
    "sim.movePoint": ("Simulation: move the microphone to point %ld", "Симуляция: перенести микрофон в точку %ld"),
    "vproc.eq.hint": ("Simulation: switch the bands on as if entering them on the processor; change the gain to see the needle move.",
                      "Симуляция: включайте полосы, как будто вводите их в процессор; меняйте усиление и смотрите на стрелку."),
    "export.copy": ("Copy filters", "Скопировать фильтры"),
    "export.text": ("Save as text…", "Сохранить как текст…"),
    "export.csv": ("Save as CSV…", "Сохранить как CSV…"),
}

DYNAMIC_PREFIXES = {
    "graph.": ["graph.magnitude", "graph.phase", "graph.coherence"],
    "wizard.step.": [f"wizard.step.{i}" for i in range(10)],
    "target.": [f"target.{p}" for p in ("flat", "livePA", "speech", "club")],
    "capture.": [f"capture.{i}.{k}" for i in (1, 2, 3, 5) for k in ("title", "text")],
    "reason.": ["reason.clipping", "reason.lowCoherence", "reason.tooFewAverages", "reason.streamDiscontinuity"],
    "verdict.": [f"verdict.{v}{t}" for v in ("excellent", "goodBut", "checkSettings") for t in ("", ".text")],
    "advice.": [f"advice.{a}" for a in ("polarityNotApplied", "delayNotApplied", "delayWrongSign", "levelMismatch", "conditionsChanged")],
}


def generate():
    catalog = {"sourceLanguage": "en", "version": "1.0", "strings": {}}
    for key in sorted(STRINGS):
        en, ru = STRINGS[key]
        catalog["strings"][key] = {
            "extractionState": "manual",
            "localizations": {
                "en": {"stringUnit": {"state": "translated", "value": en}},
                "ru": {"stringUnit": {"state": "translated", "value": ru}},
            },
        }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(catalog, f, ensure_ascii=False, indent=2)
        f.write("\n")


def check():
    used = set()
    for dirpath, _, files in os.walk(os.path.join(ROOT, "App")):
        for name in files:
            if name.endswith(".swift"):
                text = open(os.path.join(dirpath, name), encoding="utf-8").read()
                used |= set(re.findall(r'\.t\("([a-z0-9.]+)"', text))
                used |= set(re.findall(r'"((?:noise|ref|graph)\.[a-z.]+)"', text))
    missing = sorted(k for k in used if k not in STRINGS and not k.endswith("."))
    for keys in DYNAMIC_PREFIXES.values():
        missing += [k for k in keys if k not in STRINGS]
    generated = json.load(open(OUT, encoding="utf-8"))
    stale = sorted(set(STRINGS) ^ set(generated["strings"]))
    if missing or stale:
        print("Missing keys:", missing)
        print("Catalog out of date:", stale)
        sys.exit(1)
    print(f"OK: {len(used)} keys used, {len(STRINGS)} defined")


if __name__ == "__main__":
    {"generate": generate, "check": check}[sys.argv[1] if len(sys.argv) > 1 else "check"]()
